import type { WowSkill } from './skill-execution-content.ts';

const R = '#FFF569'; // rogue class color

/** Rogue kit — energy-fueled combo strikes. Costs are energy (class resource); combo:'build' adds points, 'spend' consumes them. */
export const ROGUE_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'sinisterStrike', name: 'Sinister Strike', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 45, cooldown: 0, damageMultiplier: 1.2, color: R, targetMode: 'enemy', combo: 'build',
    description: 'An instant strike against your target. Awards 1 combo point.',
    execution: { kind: 'comboStrike', build: 1 } },
  { id: 'eviscerate', name: 'Eviscerate', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 1.8, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that deals damage per combo point spent.',
    execution: { kind: 'comboStrike', spend: true } },
  { id: 'rogueBackstab', name: 'Backstab', classId: 'rogue', requirement: 'dagger', domain: 'Cunning', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 2.0, color: R, targetMode: 'enemy', combo: 'build', requiresBehind: true,
    description: 'Stab your target in the back. Must be behind the target. Awards 1 combo point.',
    execution: { kind: 'comboStrike', build: 1, requiresBehind: true } },
  { id: 'ambush', name: 'Ambush', classId: 'rogue', requirement: 'dagger', domain: 'Cunning', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 2.5, color: R, targetMode: 'enemy', combo: 'build', requiresStealth: true,
    description: 'Strike from the shadows for massive damage. Must be stealthed. Awards 2 combo points.',
    execution: { kind: 'comboStrike', build: 2, requiresStealth: true } },
  { id: 'garrote', name: 'Garrote', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 50, cooldown: 0, damageMultiplier: 0.6, color: R, targetMode: 'enemy', combo: 'build', requiresStealth: true,
    description: 'Silence your target\'s throat, bleeding it for 18 seconds. Must be stealthed. Awards 1 combo point.',
    execution: { kind: 'comboStrike', build: 1, requiresStealth: true, dot: { school: 'bleed', dpsMultiplier: 0.15, duration: 18 } } },
  { id: 'rupture', name: 'Rupture', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.4, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that wounds your target: it bleeds, longer per combo point spent.',
    execution: { kind: 'comboStrike', spend: true, dot: { school: 'bleed', dpsMultiplier: 0.2, duration: 8 } } },
  { id: 'kidneyShot', name: 'Kidney Shot', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 20, damageMultiplier: 0.3, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that stuns your target for 1 second per combo point spent.',
    execution: { kind: 'comboStrike', spend: true, stunPerCombo: 1 } },
  { id: 'sliceAndDice', name: 'Slice and Dice', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that increases your attack speed by 30%, longer per combo point spent.',
    execution: { kind: 'comboStrike', spend: true, buffPerCombo: { duration: 4, stats: { attackSpeedPercent: 30 } } } },
  { id: 'stealth', name: 'Stealth', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 6, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Melt into the shadows, becoming invisible to enemies beyond 25 units for 10 seconds.',
    execution: { kind: 'stealth', duration: 10 } },
  { id: 'vanish', name: 'Vanish', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Vanish from sight, dropping all enemy aggro and entering stealth for 10 seconds.',
    execution: { kind: 'stealth', duration: 10, dropAggro: true } },
  { id: 'sap', name: 'Sap', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 65, cooldown: 0, damageMultiplier: 0, color: R, targetMode: 'enemy', requiresStealth: true, offGcd: true,
    description: 'Incapacitate your target for 6 seconds without breaking stealth. Must be stealthed.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 6 } },
  { id: 'gouge', name: 'Gouge', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 45, cooldown: 10, damageMultiplier: 0.4, color: R, targetMode: 'enemy',
    description: 'Strike your target\'s eyes, incapacitating it for 3 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 3 } },
  { id: 'kick', name: 'Kick', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 15, cooldown: 10, damageMultiplier: 0.3, color: R, targetMode: 'enemy',
    description: 'Interrupt your target\'s attack, silencing it for 4 seconds.',
    execution: { kind: 'interrupt', silence: 4 } },
  { id: 'sprint', name: 'Sprint', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Burst of speed: move 50% faster for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, stats: { moveSpeedPercent: 50 } } } },
  { id: 'evasion', name: 'Evasion', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Dodge and weave, reducing all damage taken by 50% for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, reduction: 0.5 } } },
  { id: 'blind', name: 'Blind', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'enemy', range: 140,
    description: 'Throw blinding powder, incapacitating your target for 5 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 5 } },
  { id: 'fanOfKnives', name: 'Fan of Knives', classId: 'rogue', requirement: 'dagger', domain: 'Cunning', tier: 'advanced',
    manaCost: 50, cooldown: 6, damageMultiplier: 0.8, color: R,
    description: 'Hurl a fan of knives, striking all nearby enemies.',
    execution: { kind: 'radial', radius: 110, melee: true } },
  { id: 'adrenalineRush', name: 'Adrenaline Rush', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 90, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Your blood runs hot: regenerate 10 energy per second for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, resourcePerSecond: 10 } } },
  { id: 'cheapShot', name: 'Cheap Shot', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 0.5, color: R, targetMode: 'enemy', combo: 'build', requiresStealth: true,
    description: 'Strike from stealth, stunning your target for 2 seconds. Awards 2 combo points.',
    execution: { kind: 'comboStrike', build: 2, requiresStealth: true, stunPerCombo: 2 } },
  { id: 'hemorrhage', name: 'Hemorrhage', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.9, color: R, targetMode: 'enemy', combo: 'build',
    description: 'A vicious strike that cracks your target\'s armor, increasing its damage taken by 10% for 15 seconds. Awards 1 combo point.',
    execution: { kind: 'comboStrike', build: 1, sunder: 0.1 } },
  { id: 'cloakOfShadows', name: 'Cloak of Shadows', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Wrap yourself in shadow: break all crowd control and resist 90% of damage for 4 seconds.',
    execution: { kind: 'cleanse', removeCc: true, buff: { duration: 4, reduction: 0.9 } } },
  { id: 'mutilate', name: 'Mutilate', classId: 'rogue', requirement: 'dagger', domain: 'Cunning', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 1.7, color: R, targetMode: 'enemy', combo: 'build',
    description: 'Attack with both daggers, dealing heavy damage — increased against poisoned targets. Awards 2 combo points.',
    execution: { kind: 'comboStrike', build: 2 } },
  { id: 'envenom', name: 'Envenom', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.5, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that drives poison into your target\'s veins, dealing nature damage over time per combo point spent.',
    execution: { kind: 'comboStrike', spend: true, dot: { school: 'nature', dpsMultiplier: 0.25, duration: 6 } } },
  { id: 'deadlyThrow', name: 'Deadly Throw', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.8, color: R, targetMode: 'enemy', range: 420,
    description: 'Hurl a poisoned knife at your target, slowing it by 50% for 6 seconds.',
    execution: { kind: 'projectile', speed: 600, radius: 4, offsets: [0], effects: { style: 'nature', slowFactor: 0.5, slowDuration: 6 } } },
  { id: 'shiv', name: 'Shiv', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.7, color: R, targetMode: 'enemy', combo: 'build',
    description: 'A quick, cheap off-hand strike that applies your weapon poison. Awards 1 combo point.',
    execution: { kind: 'comboStrike', build: 1 } },
  { id: 'feint', name: 'Feint', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: R, targetMode: 'self',
    description: 'Feint and roll with incoming blows, reducing damage taken by 50% for 6 seconds.',
    execution: { kind: 'buff', buff: { duration: 6, reduction: 0.5 } } },
  { id: 'distract', name: 'Distract', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: R,
    description: 'Toss a distraction that draws nearby enemies\' attention, incapacitating them for 4 seconds.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 4, radius: 100, maxTargets: 4 } },
  { id: 'dismantle', name: 'Dismantle', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'enemy',
    description: 'Strip your target\'s weapon, disarming and incapacitating it for 6 seconds.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 6 } },
  { id: 'tricksOfTheTrade', name: 'Tricks of the Trade', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 15, cooldown: 30, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Misdirect your enemies, increasing your damage by 15% for 6 seconds.',
    execution: { kind: 'buff', buff: { duration: 6, stats: { damagePercent: 15 } } } },
  { id: 'preparation', name: 'Preparation', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 300, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Gather your focus and refresh your readiness, regenerating 20 energy per second for 3 seconds.',
    execution: { kind: 'buff', buff: { duration: 3, resourcePerSecond: 20 } } },
  { id: 'shadowstep', name: 'Shadowstep', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 10, cooldown: 30, damageMultiplier: 0, color: R, targetMode: 'enemy', range: 350,
    description: 'Step through the shadows to your target, increasing your damage by 20% for 10 seconds.',
    execution: { kind: 'dash', duration: 0.2, speed: 1200, radius: 24, toTarget: true, buff: { duration: 10, stats: { damagePercent: 20 } } } },
  { id: 'shadowDance', name: 'Shadow Dance', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Dance through the shadows, slipping into stealth for 6 seconds even while in combat.',
    execution: { kind: 'buff', buff: { duration: 6, stealth: true } } },
  { id: 'killingSpree', name: 'Killing Spree', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 120, damageMultiplier: 2.5, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move: unleash a relentless flurry of strikes, damage per combo point spent.',
    execution: { kind: 'comboStrike', spend: true } },
  { id: 'hungerForBlood', name: 'Hunger for Blood', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: R, targetMode: 'enemy',
    description: 'The scent of blood enrages you: increase all damage dealt by 15% for 60 seconds.',
    execution: { kind: 'buff', buff: { duration: 60, stats: { damagePercent: 15 } } } },
  { id: 'exposeArmor', name: 'Expose Armor', classId: 'rogue', requirement: 'melee', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.3, color: R, targetMode: 'enemy', combo: 'spend',
    description: 'Finishing move that exposes your target\'s armor, increasing its damage taken by 20%.',
    execution: { kind: 'comboStrike', spend: true, sunder: 0.2 } },
  { id: 'cripplingPoison', name: 'Crippling Poison', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 3, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Coat your weapons with crippling poison for 2 minutes: strikes deal nature damage and slow the target.',
    execution: { kind: 'buff', buff: { duration: 120, exclusiveGroup: 'poison', imbue: { element: 'nature', fraction: 0.1 } } } },
  { id: 'deadlyPoison', name: 'Deadly Poison', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 3, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Coat your weapons with deadly poison for 2 minutes: strikes deal additional nature damage.',
    execution: { kind: 'buff', buff: { duration: 120, exclusiveGroup: 'poison', imbue: { element: 'nature', fraction: 0.15 } } } },
  { id: 'woundPoison', name: 'Wound Poison', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 3, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Coat your weapons with wound poison for 2 minutes: strikes deal nature damage and hinder the target\'s healing.',
    execution: { kind: 'buff', buff: { duration: 120, exclusiveGroup: 'poison', imbue: { element: 'nature', fraction: 0.12 } } } },
  { id: 'instantPoison', name: 'Instant Poison', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 3, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Coat your weapons with instant poison for 2 minutes: strikes deal heavy additional nature damage.',
    execution: { kind: 'buff', buff: { duration: 120, exclusiveGroup: 'poison', imbue: { element: 'nature', fraction: 0.2 } } } },
  { id: 'mindNumbingPoison', name: 'Mind-Numbing Poison', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 3, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Coat your weapons with mind-numbing poison for 2 minutes: strikes deal nature damage and slow the target\'s casting.',
    execution: { kind: 'buff', buff: { duration: 120, exclusiveGroup: 'poison', imbue: { element: 'nature', fraction: 0.08 } } } },
  { id: 'detectTraps', name: 'Detect Traps', classId: 'rogue', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: R, targetMode: 'self', offGcd: true,
    description: 'Heighten your senses for 30 seconds, sharpening your critical edge.',
    execution: { kind: 'buff', buff: { duration: 30, stats: { critChance: 5 } } } },
]);
