import type { WowSkill } from './skill-execution-content.ts';

const S = '#0070DE'; // shaman class color

/** Shaman kit — elemental spells, totems and ancestral healing. Costs are mana (class resource). */
export const SHAMAN_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'lightningBolt', name: 'Lightning Bolt', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 1.6, color: S, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Hurl a bolt of lightning at your target after a 1.5 second cast.',
    execution: { kind: 'projectile', speed: 520, radius: 5, offsets: [0], effects: { style: 'lightning' } } },
  { id: 'chainLightning', name: 'Chain Lightning', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 6, damageMultiplier: 1.3, color: S, targetMode: 'enemy', range: 420,
    description: 'Strike your target with lightning that arcs to 3 nearby enemies.',
    execution: { kind: 'chain', travelSpeed: 1400, jumps: 3, range: 160, falloff: 0.7, duration: 0.3, style: 'lightning' } },
  { id: 'earthShock', name: 'Earth Shock', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 6, damageMultiplier: 0.9, color: S, targetMode: 'enemy', range: 280,
    description: 'Shock your target with earthen force, silencing it for 2 seconds.',
    execution: { kind: 'strike', school: 'nature', silence: 2 } },
  { id: 'flameShock', name: 'Flame Shock', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 6, damageMultiplier: 0.6, color: S, targetMode: 'enemy', range: 280,
    description: 'Sear your target with flame, dealing fire damage over 12 seconds.',
    execution: { kind: 'strike', school: 'fire', dot: { school: 'fire', dpsMultiplier: 0.18, duration: 12 } } },
  { id: 'frostShock', name: 'Frost Shock', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 6, damageMultiplier: 0.7, color: S, targetMode: 'enemy', range: 280,
    description: 'Chill your target with frost, slowing it by 50% for 4 seconds.',
    execution: { kind: 'strike', school: 'frost', slow: { duration: 4, factor: 0.5 } } },
  { id: 'lavaBurst', name: 'Lava Burst', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 8, damageMultiplier: 1.4, color: S, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Hurl molten lava at your target after a 1.5 second cast. Deals 50% more damage to enemies burning with Flame Shock.',
    execution: { kind: 'strike', school: 'fire', bonusVsDot: 0.5 } },
  { id: 'stormstrike', name: 'Stormstrike', classId: 'shaman', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 20, cooldown: 8, damageMultiplier: 1.8, color: S, targetMode: 'enemy',
    description: 'Strike your target with both weapons, charging them with storm energy.',
    execution: { kind: 'strike' } },
  { id: 'windShear', name: 'Wind Shear', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 15, cooldown: 6, damageMultiplier: 0.2, color: S, targetMode: 'enemy', range: 350, offGcd: true,
    description: 'A gust of wind that interrupts your target, silencing it for 3 seconds.',
    execution: { kind: 'interrupt', silence: 3 } },
  { id: 'healingWave', name: 'Healing Wave', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', castTime: 2,
    description: 'Call on ancestral waters to mend your wounds after a 2 second cast.',
    execution: { kind: 'heal', amount: 2.6 } },
  { id: 'lesserHealingWave', name: 'Lesser Healing Wave', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', castTime: 1,
    description: 'A quick surge of healing that mends your wounds after a 1 second cast.',
    execution: { kind: 'heal', amount: 1.3 } },
  { id: 'chainHeal', name: 'Chain Heal', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 6, damageMultiplier: 0, color: S, targetMode: 'self', castTime: 1.5,
    description: 'A wave of healing that mends your wounds and continues to restore health over 9 seconds.',
    execution: { kind: 'heal', amount: 1.6, hot: { perTick: 0.15, duration: 9 } } },
  { id: 'searingTotem', name: 'Searing Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that sears nearby enemies with fire for 30 seconds.',
    execution: { kind: 'summon', ally: 'searingTotem', count: 1, duration: 30 } },
  { id: 'healingStreamTotem', name: 'Healing Stream Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that mends your wounds over time for 30 seconds.',
    execution: { kind: 'summon', ally: 'healingTotem', count: 1, duration: 30 } },
  { id: 'earthbindTotem', name: 'Earthbind Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that slows nearby enemies for 20 seconds.',
    execution: { kind: 'summon', ally: 'earthbindTotem', count: 1, duration: 20 } },
  { id: 'ghostWolf', name: 'Ghost Wolf', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Transform into a spectral wolf, increasing movement speed by 30%.',
    execution: { kind: 'form', form: 'ghostWolf', buff: { duration: 3600, exclusiveGroup: 'form', form: 'ghostWolf', stats: { moveSpeedPercent: 30 } } } },
  { id: 'bloodlust', name: 'Bloodlust', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 30, cooldown: 120, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Fill yourself with primal fury, increasing attack and cast speed by 20% for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, stats: { attackSpeedPercent: 20, castSpeedPercent: 20 } } } },
  { id: 'feralSpirit', name: 'Feral Spirit', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 40, cooldown: 90, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Summon two spirit wolves to fight at your side for 30 seconds.',
    execution: { kind: 'summon', ally: 'spiritWolf', count: 2, duration: 30 } },
  { id: 'thunderstorm', name: 'Thunderstorm', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 20, damageMultiplier: 1.0, color: S,
    description: 'Call down a storm that blasts nearby enemies with lightning, stunning them for 1.5 seconds.',
    execution: { kind: 'radial', radius: 130, melee: false, stun: 1.5, style: 'lightning' } },
  { id: 'lightningShield', name: 'Lightning Shield', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Surround yourself with lightning, reflecting 30% of incoming damage for 5 minutes. Only one shield can be active.',
    execution: { kind: 'buff', buff: { duration: 300, exclusiveGroup: 'shield', reflect: 0.3 } } },
  { id: 'windfuryWeapon', name: 'Windfury Weapon', classId: 'shaman', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Imbue your weapon with wind for 30 minutes; strikes deal additional lightning damage. Only one imbue can be active.',
    execution: { kind: 'buff', buff: { duration: 1800, exclusiveGroup: 'imbue', imbue: { element: 'lightning', fraction: 0.35 } } } },
  { id: 'flametongueWeapon', name: 'Flametongue Weapon', classId: 'shaman', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Imbue your weapon with flame for 30 minutes; strikes deal additional fire damage. Only one imbue can be active.',
    execution: { kind: 'buff', buff: { duration: 1800, exclusiveGroup: 'imbue', imbue: { element: 'fire', fraction: 0.25 } } } },
  { id: 'frostbrandWeapon', name: 'Frostbrand Weapon', classId: 'shaman', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Imbue your weapon with frost for 30 minutes; strikes deal additional frost damage. Only one imbue can be active.',
    execution: { kind: 'buff', buff: { duration: 1800, exclusiveGroup: 'imbue', imbue: { element: 'frost', fraction: 0.3 } } } },
  { id: 'rockbiterWeapon', name: 'Rockbiter Weapon', classId: 'shaman', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Imbue your weapon with earthen weight for 30 minutes; strikes deal additional nature damage. Only one imbue can be active.',
    execution: { kind: 'buff', buff: { duration: 1800, exclusiveGroup: 'imbue', imbue: { element: 'nature', fraction: 0.2 } } } },
  { id: 'earthlivingWeapon', name: 'Earthliving Weapon', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Imbue your weapon with life-giving earth for 30 minutes, mending your wounds over time. Only one imbue can be active.',
    execution: { kind: 'buff', buff: { duration: 1800, exclusiveGroup: 'imbue', imbue: { element: 'nature', fraction: 0.15 }, healPerSecond: 0.004 } } },
  { id: 'fireNova', name: 'Fire Nova', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 10, damageMultiplier: 1.1, color: S,
    description: 'Unleash a nova of fire that burns all nearby enemies.',
    execution: { kind: 'radial', radius: 140, melee: false, style: 'fire' } },
  { id: 'magmaTotem', name: 'Magma Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that erupts with magma, searing nearby enemies for 30 seconds.',
    execution: { kind: 'summon', ally: 'magmaTotem', count: 1, duration: 30 } },
  { id: 'manaSpringTotem', name: 'Mana Spring Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that restores your mana over time for 45 seconds.',
    execution: { kind: 'summon', ally: 'manaSpringTotem', count: 1, duration: 45 } },
  { id: 'totemOfWrath', name: 'Totem of Wrath', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem of wrath that empowers your spells and sears nearby enemies for 45 seconds.',
    execution: { kind: 'summon', ally: 'totemOfWrath', count: 1, duration: 45 } },
  { id: 'wrathOfAirTotem', name: 'Wrath of Air Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that quickens your spellcasting for 45 seconds.',
    execution: { kind: 'summon', ally: 'wrathOfAirTotem', count: 1, duration: 45 } },
  { id: 'windfuryTotem', name: 'Windfury Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that quickens your attacks for 45 seconds.',
    execution: { kind: 'summon', ally: 'windfuryTotem', count: 1, duration: 45 } },
  { id: 'strengthOfEarthTotem', name: 'Strength of Earth Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that lends you the strength of the earth for 45 seconds.',
    execution: { kind: 'summon', ally: 'strengthOfEarthTotem', count: 1, duration: 45 } },
  { id: 'stoneskinTotem', name: 'Stoneskin Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that hardens your skin like stone for 45 seconds.',
    execution: { kind: 'summon', ally: 'stoneskinTotem', count: 1, duration: 45 } },
  { id: 'flametongueTotem', name: 'Flametongue Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem wreathed in flame that sears nearby enemies for 45 seconds.',
    execution: { kind: 'summon', ally: 'flametongueTotem', count: 1, duration: 45 } },
  { id: 'tremorTotem', name: 'Tremor Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that trembles the ground, steadying you against fear for 30 seconds.',
    execution: { kind: 'summon', ally: 'tremorTotem', count: 1, duration: 30 } },
  { id: 'cleansingTotem', name: 'Cleansing Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that cleanses you of poison and disease for 30 seconds.',
    execution: { kind: 'summon', ally: 'cleansingTotem', count: 1, duration: 30 } },
  { id: 'groundingTotem', name: 'Grounding Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 15, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that grounds hostile magic, slowing nearby enemies for 30 seconds.',
    execution: { kind: 'summon', ally: 'groundingTotem', count: 1, duration: 30 } },
  { id: 'earthElementalTotem', name: 'Earth Elemental Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 50, cooldown: 180, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that calls forth an earth elemental to protect you for 45 seconds.',
    execution: { kind: 'summon', ally: 'earthElemental', count: 1, duration: 45 } },
  { id: 'fireElementalTotem', name: 'Fire Elemental Totem', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 50, cooldown: 180, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'Place a totem that calls forth a fire elemental to burn your enemies for 45 seconds.',
    execution: { kind: 'summon', ally: 'fireElemental', count: 1, duration: 45 } },
  { id: 'purge', name: 'Purge', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'enemy', range: 280,
    description: 'Purge your target with elemental force, dealing Nature damage and silencing it for 2 seconds.',
    execution: { kind: 'strike', school: 'nature', silence: 2 } },
  { id: 'hex', name: 'Hex', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 45, damageMultiplier: 0, color: S, targetMode: 'enemy', range: 280,
    description: 'Transform your target into a frog for 6 seconds. Any damage may break the effect.',
    execution: { kind: 'cc', cc: 'polymorph', duration: 6 } },
  { id: 'riptide', name: 'Riptide', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 6, damageMultiplier: 0, color: S, targetMode: 'self',
    description: 'A surge of water that mends your wounds and continues to heal over 9 seconds.',
    execution: { kind: 'heal', amount: 1.4, hot: { perTick: 0.12, duration: 9 } } },
  { id: 'earthShield', name: 'Earth Shield', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Surround yourself with earthen plates that absorb 25% of your maximum health in damage for 60 seconds. Only one shield can be active.',
    execution: { kind: 'buff', buff: { duration: 60, exclusiveGroup: 'shield', absorb: 0.25 } } },
  { id: 'waterShield', name: 'Water Shield', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Surround yourself with globes of water that restore your mana for 5 minutes. Only one shield can be active.',
    execution: { kind: 'buff', buff: { duration: 300, exclusiveGroup: 'shield', manaPerSecond: 0.005 } } },
  { id: 'ancestralSpirit', name: 'Ancestral Spirit', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: S, targetMode: 'self', castTime: 8,
    description: 'Call an ancestral spirit back from beyond, restoring 40% of your maximum health after an 8 second cast.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.4 } },
  { id: 'reincarnation', name: 'Reincarnation', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 0, cooldown: 600, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true,
    description: 'Bind your spirit to the world for 5 minutes; ancestral energy slowly mends your wounds.',
    execution: { kind: 'buff', buff: { duration: 300, healPerSecond: 0.003 } } },
  { id: 'astralRecall', name: 'Astral Recall', classId: 'shaman', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 10, cooldown: 300, damageMultiplier: 0, color: S, targetMode: 'self', offGcd: true, castTime: 5,
    description: 'Recall your spirit through the astral plane, moving 50% faster for 6 seconds after a 5 second cast.',
    execution: { kind: 'buff', buff: { duration: 6, stats: { moveSpeedPercent: 50 } } } },
]);
