import type { WowSkill } from './skill-execution-content.ts';

const P = '#F58CBA'; // paladin class color

/** Paladin kit — holy mana. Costs are mana (class resource). */
export const PALADIN_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'crusaderStrike', name: 'Crusader Strike', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 30, cooldown: 4, damageMultiplier: 1.1, color: P, targetMode: 'enemy',
    description: 'An instant strike that deals weapon damage plus Holy damage.',
    execution: { kind: 'strike', school: 'holy' } },
  { id: 'judgement', name: 'Judgement', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 25, cooldown: 8, damageMultiplier: 1.0, color: P, targetMode: 'enemy', range: 140,
    description: 'Judge your target with Holy power, increasing its damage taken by 10% for 15 seconds.',
    execution: { kind: 'strike', school: 'holy', sunder: 0.1 } },
  { id: 'sealOfCommand', name: 'Seal of Command', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with Holy power for 30 seconds; your melee swings deal additional Holy damage.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', imbue: { element: 'holy', fraction: 0.3 } } } },
  { id: 'consecration', name: 'Consecration', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 12, damageMultiplier: 0.4, color: P, targetMode: 'point',
    description: 'Consecrate the ground, dealing Holy damage to enemies in the area for 9 seconds.',
    execution: { kind: 'ground', effect: 'storm', radius: 110, delay: 0.3, duration: 9, interval: 1, style: 'radiant' } },
  { id: 'hammerOfJustice', name: 'Hammer of Justice', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 140,
    description: 'Stun your target for 4 seconds.',
    execution: { kind: 'cc', cc: 'stun', duration: 4 } },
  { id: 'holyLight', name: 'Holy Light', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 2,
    description: 'A slow, powerful heal that restores 50% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.5 } },
  { id: 'flashOfLight', name: 'Flash of Light', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 1,
    description: 'A quick, efficient heal that restores 25% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.25 } },
  { id: 'divineShield', name: 'Divine Shield', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 20, cooldown: 120, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'An impenetrable shield makes you immune to all damage for 6 seconds.',
    execution: { kind: 'buff', buff: { duration: 6, immunity: true } } },
  { id: 'divineProtection', name: 'Divine Protection', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 15, cooldown: 30, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Reduce all damage taken by 50% for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, reduction: 0.5 } } },
  { id: 'layOnHands', name: 'Lay on Hands', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 0, cooldown: 300, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'A massive surge that restores 100% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 1 } },
  { id: 'avengingWrath', name: 'Avenging Wrath', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 0, cooldown: 90, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Unfurl wings of holy power, increasing all damage dealt by 20% for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { damagePercent: 20, spellDamagePercent: 20 } } } },
  { id: 'hammerOfWrath', name: 'Hammer of Wrath', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 6, damageMultiplier: 1.8, color: P, targetMode: 'enemy', range: 420, executeThreshold: 0.2,
    description: 'Hurl a holy hammer at a wounded enemy. Only usable below 20% health.',
    execution: { kind: 'strike', school: 'holy' } },
  { id: 'exorcism', name: 'Exorcism', classId: 'paladin', requirement: 'melee', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 15, damageMultiplier: 1.8, color: P, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Banish the wicked with Holy wrath, dealing heavy Holy damage.',
    execution: { kind: 'strike', school: 'holy' } },
  { id: 'holyShock', name: 'Holy Shock', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 55, cooldown: 8, damageMultiplier: 1.2, color: P, targetMode: 'enemy', range: 280,
    description: 'Shock your target with Holy energy, restoring health equal to 50% of the damage dealt.',
    execution: { kind: 'strike', school: 'holy', healFrac: 0.5 } },
  { id: 'repentance', name: 'Repentance', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 280,
    description: 'Force your target to repent, incapacitating it for 6 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 6 } },
  { id: 'blessingOfKings', name: 'Blessing of Kings', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A blessing that increases all of your combat effectiveness for 5 minutes.',
    execution: { kind: 'buff', buff: { duration: 300, stats: { damagePercent: 6, spellDamagePercent: 6, critChance: 2, moveSpeedPercent: 5 } } } },
  { id: 'divineStorm', name: 'Divine Storm', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'ultimate',
    manaCost: 40, cooldown: 20, damageMultiplier: 1.6, color: P,
    description: 'A whirling storm of Holy power strikes all nearby enemies.',
    execution: { kind: 'radial', radius: 120, melee: true, style: 'radiant' } },
  { id: 'holyShield', name: 'Holy Shield', classId: 'paladin', requirement: 'shield', domain: 'Arcana', tier: 'advanced',
    manaCost: 15, cooldown: 8, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Raise a holy shield: +30% block chance and reflect 30% of damage taken for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stats: { blockChance: 30 }, reflect: 0.3 } } },
  { id: 'blessingOfMight', name: 'Blessing of Might', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A blessing that increases attack power, raising damage dealt by 15% for 5 minutes.',
    execution: { kind: 'buff', buff: { duration: 300, exclusiveGroup: 'blessing', stats: { damagePercent: 15 } } } },
  { id: 'blessingOfWisdom', name: 'Blessing of Wisdom', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A blessing that restores mana over time for 5 minutes.',
    execution: { kind: 'buff', buff: { duration: 300, exclusiveGroup: 'blessing', manaPerSecond: 0.01 } } },
  { id: 'blessingOfSanctuary', name: 'Blessing of Sanctuary', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A blessing that reduces damage taken by 3% and bolsters strength and stamina for 5 minutes.',
    execution: { kind: 'buff', buff: { duration: 300, exclusiveGroup: 'blessing', reduction: 0.03, stats: { strength: 3, vitality: 3 } } } },
  { id: 'handOfFreedom', name: 'Hand of Freedom', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 25, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Break free of movement-impairing effects and become immune to them for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, breakControl: true } } },
  { id: 'handOfProtection', name: 'Hand of Protection', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 90, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'A protective hand that absorbs damage equal to half your health for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, absorb: 0.5 } } },
  { id: 'handOfSacrifice', name: 'Hand of Sacrifice', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Sacrifice yourself to shield an ally, reducing damage taken by 30% for 12 seconds.',
    execution: { kind: 'buff', buff: { duration: 12, reduction: 0.3 } } },
  { id: 'handOfSalvation', name: 'Hand of Salvation', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Fade from enemy sight, shedding threat for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, stealth: true } } },
  { id: 'divineSacrifice', name: 'Divine Sacrifice', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 30, cooldown: 120, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Redirect harm to yourself, reducing all damage taken by 40% for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, reduction: 0.4 } } },
  { id: 'divinePlea', name: 'Divine Plea', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Plead for divine favor, restoring 25% of your mana over 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, manaPerSecond: 0.017 } } },
  { id: 'shieldOfRighteousness', name: 'Shield of Righteousness', classId: 'paladin', requirement: 'shield', domain: 'Might', tier: 'advanced',
    manaCost: 30, cooldown: 6, damageMultiplier: 1.6, color: P, targetMode: 'enemy',
    description: 'Slam the target with your shield, dealing Holy damage based on your block value.',
    execution: { kind: 'strike', school: 'holy' } },
  { id: 'hammerOfTheRighteous', name: 'Hammer of the Righteous', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 30, cooldown: 6, damageMultiplier: 1.2, color: P, targetMode: 'enemy',
    description: 'Hammer the current target and nearby enemies with Holy damage.',
    execution: { kind: 'sweep', reachMultiplier: 1.3, arc: Math.PI * 1.5 } },
  { id: 'avengersShield', name: "Avenger's Shield", classId: 'paladin', requirement: 'shield', domain: 'Might', tier: 'ultimate',
    manaCost: 35, cooldown: 30, damageMultiplier: 1.4, color: P, targetMode: 'enemy', range: 420,
    description: 'Hurl your shield at an enemy; it ricochets to two more targets, dealing Holy damage and slowing them.',
    execution: { kind: 'chain', jumps: 3, range: 160, falloff: 0.8, duration: 0.3, style: 'radiant', slow: { duration: 4, factor: 0.5 } } },
  { id: 'judgementOfLight', name: 'Judgement of Light', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 25, cooldown: 8, damageMultiplier: 1.0, color: P, targetMode: 'enemy', range: 140,
    description: 'Judge your target with Holy power, healing you for 30% of the damage dealt.',
    execution: { kind: 'strike', school: 'holy', healFrac: 0.3 } },
  { id: 'judgementOfWisdom', name: 'Judgement of Wisdom', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 25, cooldown: 8, damageMultiplier: 1.0, color: P, targetMode: 'point', range: 140,
    description: 'Judge your target with Holy power, restoring 25 mana.',
    execution: { kind: 'radial', targetRange: 140, radius: 60, melee: false, style: 'radiant', resourceGain: 25 } },
  { id: 'judgementOfJustice', name: 'Judgement of Justice', classId: 'paladin', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 25, cooldown: 8, damageMultiplier: 1.0, color: P, targetMode: 'enemy', range: 140,
    description: 'Judge your target with Holy power, slowing its movement by 50% for 4 seconds.',
    execution: { kind: 'strike', school: 'holy', slow: { duration: 4, factor: 0.5 } } },
  { id: 'sealOfVengeance', name: 'Seal of Vengeance', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with Holy power for 30 seconds; your melee swings deal additional Holy damage.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', imbue: { element: 'holy', fraction: 0.25 } } } },
  { id: 'sealOfRighteousness', name: 'Seal of Righteousness', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with Holy power for 30 seconds; your melee swings deal additional Holy damage. Cheap to maintain.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', imbue: { element: 'holy', fraction: 0.25 } } } },
  { id: 'sealOfCorruption', name: 'Seal of Corruption', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with vengeful power for 30 seconds; your melee swings deal additional Holy damage.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', imbue: { element: 'holy', fraction: 0.25 } } } },
  { id: 'sealOfWisdom', name: 'Seal of Wisdom', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with Holy power for 30 seconds; your melee swings restore mana.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', manaPerSecond: 0.01 } } },
  { id: 'sealOfLight', name: 'Seal of Light', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Fill yourself with Holy power for 30 seconds; your melee swings restore health.',
    execution: { kind: 'buff', buff: { duration: 30, exclusiveGroup: 'seal', healPerSecond: 0.01 } } },
  { id: 'righteousFury', name: 'Righteous Fury', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Channel righteous fury, increasing your threat and damage dealt by 10%.',
    execution: { kind: 'buff', buff: { duration: 300, stats: { damagePercent: 10 } } } },
  { id: 'divineIllumination', name: 'Divine Illumination', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Divine clarity reduces the mana cost of your spells by 50% for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { manaCostPercent: 50 } } } },
  { id: 'beaconOfLight', name: 'Beacon of Light', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Become a beacon of healing, regenerating health over 60 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, healPerSecond: 0.02 } } },
  { id: 'holyWrath', name: 'Holy Wrath', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 30, damageMultiplier: 1.2, color: P, targetMode: 'point',
    description: 'Unleash a burst of Holy energy, damaging and stunning all nearby enemies for 2 seconds.',
    execution: { kind: 'radial', radius: 130, melee: false, stun: 2, style: 'radiant' } },
  { id: 'turnEvil', name: 'Turn Evil', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 30, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 280, castTime: 1.5,
    description: 'Fill an undead or demon target with holy fear, forcing it to flee for 10 seconds.',
    execution: { kind: 'cc', cc: 'fear', duration: 10 } },
  { id: 'purify', name: 'Purify', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Purify yourself, removing poison and disease effects.',
    execution: { kind: 'cleanse', removeCc: true } },
  { id: 'cleanse', name: 'Cleanse', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Cleanse yourself of magic, poison, and disease, mending 10% of your health.',
    execution: { kind: 'cleanse', removeCc: true, heal: 0.1 } },
  { id: 'redemption', name: 'Redemption', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 10,
    description: 'A long invocation that restores 60% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.6 } },
  { id: 'sacredShield', name: 'Sacred Shield', classId: 'paladin', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 6, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A sacred barrier absorbs damage equal to 25% of your health for 30 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, absorb: 0.25 } } },
]);
