import type { WowSkill } from './skill-execution-content.ts';

/** Racial actives — one per race, auto-known on the R slot. All are free, off the global cooldown and self-targeted. */
export const RACIAL_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'everyMan', name: 'Every Man for Himself', raceId: 'human', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#e8c05a', targetMode: 'self', offGcd: true,
    description: 'Break all stuns, roots and control effects, and take 30% less damage for 2 seconds.',
    execution: { kind: 'cleanse', removeCc: true, buff: { duration: 2, reduction: 0.3 } } },
  { id: 'stoneform', name: 'Stoneform', raceId: 'dwarf', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#c9a86a', targetMode: 'self', offGcd: true,
    description: 'Harden your skin: shed control effects and take 30% less damage for 2 seconds.',
    execution: { kind: 'cleanse', removeCc: true, buff: { duration: 2, reduction: 0.3 } } },
  { id: 'shadowmeld', name: 'Shadowmeld', raceId: 'nightElf', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#8a9fd8', targetMode: 'self', offGcd: true,
    description: 'Fade into shadow for 6 seconds, hidden from distant enemies.',
    execution: { kind: 'stealth', duration: 6 } },
  { id: 'escapeArtist', name: 'Escape Artist', raceId: 'gnome', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 105, damageMultiplier: 0, color: '#e08fb8', targetMode: 'self', offGcd: true,
    description: 'Slip free of roots, slows and control effects, moving 30% faster for 3 seconds.',
    execution: { kind: 'cleanse', removeCc: true, buff: { duration: 3, stats: { moveSpeedPercent: 30 } } } },
  { id: 'giftNaaru', name: 'Gift of the Naaru', raceId: 'draenei', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: '#7fb8e8', targetMode: 'self', offGcd: true,
    description: 'Blessed light restores 20% of your maximum life over 5 seconds.',
    execution: { kind: 'hot', maxHpFrac: 0.2, hot: { perTick: 0, duration: 5, interval: 1 } } },
  { id: 'bloodFury', name: 'Blood Fury', raceId: 'orc', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#d85a3a', targetMode: 'self', offGcd: true,
    description: 'Unleash your fury: +15% damage for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { damagePercent: 15, spellDamagePercent: 15 } } } },
  { id: 'willForsaken', name: 'Will of the Forsaken', raceId: 'undead', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#7a9a8a', targetMode: 'self', offGcd: true,
    description: 'Shake off fear and all control effects, taking 30% less damage for 2 seconds.',
    execution: { kind: 'cleanse', removeCc: true, buff: { duration: 2, reduction: 0.3 } } },
  { id: 'warStomp', name: 'War Stomp', raceId: 'tauren', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#c98a4a', targetMode: 'self', offGcd: true,
    description: 'Stomp the ground, stunning nearby enemies for 1.5 seconds.',
    execution: { kind: 'cc', cc: 'stun', duration: 1.5, radius: 100 } },
  { id: 'berserking', name: 'Berserking', raceId: 'troll', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: '#4ac8a0', targetMode: 'self', offGcd: true,
    description: 'Enter a frenzy: +20% attack and cast speed for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stats: { attackSpeedPercent: 20, castSpeedPercent: 20 } } } },
  { id: 'arcaneTorrent', name: 'Arcane Torrent', raceId: 'bloodElf', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: '#e87ad0', targetMode: 'self', offGcd: true,
    description: 'Silence nearby enemies for 2 seconds and restore 15 resource.',
    execution: { kind: 'cc', cc: 'silence', duration: 2, radius: 100, resourceGain: 15 } },
]);
