import type { WowSkill } from './skill-execution-content.ts';

const D = '#FF7D0A'; // druid class color

/** Druid kit — caster spells cost mana; feral strikes spend the form's resource (bear=rage, cat=energy+combo). */
export const DRUID_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'wrath', name: 'Wrath', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 1.4, color: D, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Hurl a bolt of nature energy at your target.',
    execution: { kind: 'projectile', speed: 460, radius: 6, offsets: [0], effects: { style: 'lightning' } } },
  { id: 'starfire', name: 'Starfire', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 0, damageMultiplier: 3.2, color: D, targetMode: 'enemy', range: 420, castTime: 2.5,
    description: 'Call down a bolt of stellar fire, causing heavy Arcane damage.',
    execution: { kind: 'projectile', speed: 380, radius: 8, offsets: [0], effects: { style: 'arcane' } } },
  { id: 'moonfire', name: 'Moonfire', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 1.0, color: D, targetMode: 'enemy', range: 420,
    description: 'Burn your target with moonfire: Arcane damage plus damage over 12 seconds.',
    execution: { kind: 'strike', school: 'arcane', dot: { school: 'arcane', dpsMultiplier: 0.15, duration: 12 } } },
  { id: 'insectSwarm', name: 'Insect Swarm', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 0, damageMultiplier: 0.4, color: D, targetMode: 'enemy', range: 420,
    description: 'Swarm your target with insects, dealing Nature damage over 12 seconds.',
    execution: { kind: 'dot', dot: { school: 'nature', dpsMultiplier: 0.15, duration: 12 } } },
  { id: 'entanglingRoots', name: 'Entangling Roots', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Root your target in place for 6 seconds.',
    execution: { kind: 'cc', cc: 'root', duration: 6 } },
  { id: 'hurricane', name: 'Hurricane', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 90, cooldown: 12, damageMultiplier: 0.5, color: D, targetMode: 'point', range: 420,
    channel: { duration: 8, ticks: 8 },
    description: 'Channel a hurricane onto the target area for 8 seconds, battering enemies with Nature damage.',
    execution: { kind: 'ground', effect: 'storm', radius: 140, delay: 0.3, duration: 8, interval: 1, style: 'lightning' } },
  { id: 'starfall', name: 'Starfall', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 100, cooldown: 90, damageMultiplier: 0.6, color: D, targetMode: 'point', range: 420,
    description: 'Call down a storm of stars for 10 seconds, striking enemies with Arcane damage.',
    execution: { kind: 'ground', effect: 'storm', radius: 160, delay: 0.3, duration: 10, interval: 1, style: 'arcane', follow: true } },
  { id: 'healingTouch', name: 'Healing Touch', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 45, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 2.5,
    description: 'A slow, powerful heal that restores a large amount of health.',
    execution: { kind: 'heal', amount: 4.0 } },
  { id: 'regrowth', name: 'Regrowth', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 2,
    description: 'Heal yourself, then continue healing over 15 seconds.',
    execution: { kind: 'heal', amount: 1.6, hot: { perTick: 0.12, duration: 15 } } },
  { id: 'rejuvenation', name: 'Rejuvenation', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Restore health over 12 seconds.',
    execution: { kind: 'hot', hot: { perTick: 0.15, duration: 12 } } },
  { id: 'swiftmend', name: 'Swiftmend', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 15, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Consume an active heal-over-time effect to instantly restore its remaining healing.',
    execution: { kind: 'heal', amount: 2.0, consumeHot: 1 } },
  { id: 'barkskin', name: 'Barkskin', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Your skin hardens like bark, reducing all damage taken by 30% for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, reduction: 0.3 } } },
  { id: 'bearForm', name: 'Bear Form', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into a bear: +60% armor and +25% maximum health, and your attacks build rage.',
    execution: { kind: 'form', form: 'bear', buff: { duration: 3600, exclusiveGroup: 'form', form: 'bear', stats: { armorPercent: 60, maxHpPercent: 25 } } } },
  { id: 'catForm', name: 'Cat Form', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into a cat: your attacks use energy and combo points, and you can prowl.',
    execution: { kind: 'form', form: 'cat', buff: { duration: 3600, exclusiveGroup: 'form', form: 'cat', stats: { damagePercent: 10, critChance: 3 } } } },
  { id: 'moonkinForm', name: 'Moonkin Form', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into a moonkin: +15% spell damage and +40% armor.',
    execution: { kind: 'form', form: 'moonkin', buff: { duration: 3600, exclusiveGroup: 'form', form: 'moonkin', stats: { spellDamagePercent: 15, armorPercent: 40 } } } },
  { id: 'travelForm', name: 'Travel Form', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into a swift travel form, increasing movement speed by 40%.',
    execution: { kind: 'form', form: 'travel', buff: { duration: 3600, exclusiveGroup: 'form', form: 'travel', stats: { moveSpeedPercent: 40 } } } },
  { id: 'maul', name: 'Maul', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 1.6, color: D, targetMode: 'enemy', resource: 'rage', requiresForm: 'bear',
    description: 'A mauling strike against your target. Bear Form only.',
    execution: { kind: 'strike' } },
  { id: 'swipe', name: 'Swipe', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 1.0, color: D, resource: 'rage', requiresForm: 'bear',
    description: 'Sweep your claws through all nearby enemies. Bear Form only.',
    execution: { kind: 'radial', radius: 110, melee: true } },
  { id: 'bash', name: 'Bash', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 60, damageMultiplier: 0.3, color: D, targetMode: 'enemy', resource: 'rage', requiresForm: 'bear',
    description: 'Stun your target for 3 seconds. Bear Form only.',
    execution: { kind: 'cc', cc: 'stun', duration: 3 } },
  { id: 'feralCharge', name: 'Feral Charge', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 15, damageMultiplier: 0.4, color: D, targetMode: 'enemy', range: 350, resource: 'rage', requiresForm: 'bear',
    description: 'Rush your target, stunning it for 1 second. Bear Form only.',
    execution: { kind: 'dash', duration: 0.3, speed: 900, radius: 24, stun: 1, toTarget: true } },
  { id: 'mangle', name: 'Mangle', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 1.5, color: D, targetMode: 'enemy', resource: 'rage', requiresForm: 'bear',
    description: 'Mangle your target, causing it to bleed over 15 seconds and increasing its damage taken by 10%. Bear Form only.',
    execution: { kind: 'strike', sunder: 0.1, dot: { school: 'bleed', dpsMultiplier: 0.15, duration: 15 } } },
  { id: 'claw', name: 'Claw', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 45, cooldown: 0, damageMultiplier: 1.2, color: D, targetMode: 'enemy', resource: 'energy', combo: 'build', requiresForm: 'cat',
    description: 'Claw your target. Awards 1 combo point. Cat Form only.',
    execution: { kind: 'comboStrike', build: 1 } },
  { id: 'rake', name: 'Rake', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.8, color: D, targetMode: 'enemy', resource: 'energy', combo: 'build', requiresForm: 'cat',
    description: 'Rake your target, causing bleeding damage over 9 seconds. Awards 1 combo point. Cat Form only.',
    execution: { kind: 'comboStrike', build: 1, dot: { school: 'bleed', dpsMultiplier: 0.15, duration: 9 } } },
  { id: 'rip', name: 'Rip', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0.4, color: D, targetMode: 'enemy', resource: 'energy', combo: 'spend', requiresForm: 'cat',
    description: 'Finishing move that makes your target bleed, longer per combo point spent. Cat Form only.',
    execution: { kind: 'comboStrike', spend: true, dot: { school: 'bleed', dpsMultiplier: 0.2, duration: 12 } } },
  { id: 'ferociousBite', name: 'Ferocious Bite', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 1.8, color: D, targetMode: 'enemy', resource: 'energy', combo: 'spend', requiresForm: 'cat',
    description: 'Finishing move that deals damage per combo point spent. Cat Form only.',
    execution: { kind: 'comboStrike', spend: true } },
  { id: 'prowl', name: 'Prowl', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 10, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, requiresForm: 'cat',
    description: 'Enter stealth, becoming invisible to enemies beyond 25 units for 10 seconds. Cat Form only.',
    execution: { kind: 'stealth', duration: 10 } },
  { id: 'pounce', name: 'Pounce', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 50, cooldown: 0, damageMultiplier: 0.5, color: D, targetMode: 'enemy', resource: 'energy', combo: 'build', requiresForm: 'cat', requiresStealth: true,
    description: 'Strike from stealth, stunning your target for 2 seconds. Awards 1 combo point. Cat Form only.',
    execution: { kind: 'comboStrike', build: 1, requiresStealth: true, stunPerCombo: 2 } },
  { id: 'faerieFire', name: 'Faerie Fire', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0.3, color: D, targetMode: 'enemy', range: 420,
    description: 'Wreathe your target in faerie light, increasing its damage taken by 5% for 15 seconds.',
    execution: { kind: 'strike', sunder: 0.05 } },
  { id: 'innervate', name: 'Innervate', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Restore 5% of your maximum mana per second for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, manaPerSecond: 0.05 } } },
  { id: 'nourish', name: 'Nourish', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 16, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 1.5,
    description: 'A quick, efficient heal that restores a moderate amount of health, empowered by your heal-over-time effects.',
    execution: { kind: 'heal', amount: 1.5 } },
  { id: 'wildGrowth', name: 'Wild Growth', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 8, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Healing energy blossoms around you, restoring health over 7 seconds.',
    execution: { kind: 'hot', hot: { perTick: 0.2, duration: 7 } } },
  { id: 'lifebloom', name: 'Lifebloom', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 28, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'A blooming heal that restores health over 9 seconds, flowering as it matures.',
    execution: { kind: 'hot', hot: { perTick: 0.12, duration: 9 }, maxHpFrac: 0.08 } },
  { id: 'tranquility', name: 'Tranquility', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 120, cooldown: 480, damageMultiplier: 1.0, color: D, targetMode: 'self',
    channel: { duration: 8, ticks: 8 },
    description: 'Channel a soothing rain for 8 seconds, mending your wounds each second.',
    execution: { kind: 'channel', school: 'nature', ticks: 8, duration: 8, healFrac: 1.5 } },
  { id: 'rebirth', name: 'Rebirth', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 80, cooldown: 600, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 2,
    description: 'A restorative surge that mends you for 60% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.6 } },
  { id: 'revive', name: 'Revive', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 10,
    description: 'Recover from a near-fatal state, restoring 35% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.35 } },
  { id: 'abolishPoison', name: 'Abolish Poison', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Abolish the poison coursing through your body, shedding harmful effects.',
    execution: { kind: 'cleanse', removeCc: true } },
  { id: 'removeCurseDruid', name: 'Remove Curse', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Lift a curse from yourself, shedding harmful effects.',
    execution: { kind: 'cleanse', removeCc: true } },
  { id: 'naturesGrasp', name: 'Nature\'s Grasp', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Thorny vines answer your attackers, reflecting 50% of damage for 45 seconds.',
    execution: { kind: 'buff', buff: { duration: 45, reflect: 0.5 } } },
  { id: 'cyclone', name: 'Cyclone', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 25, cooldown: 30, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 280, castTime: 1.5,
    description: 'Hurl your target into the air on a violent cyclone, incapacitating it for 6 seconds.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 6 } },
  { id: 'typhoon', name: 'Typhoon', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0.8, color: D,
    description: 'Summon a violent typhoon that knocks back and slows nearby enemies for 3 seconds.',
    execution: { kind: 'radial', radius: 130, melee: false, slow: { duration: 3, factor: 0.5 }, style: 'lightning' } },
  { id: 'forceOfNature', name: 'Force of Nature', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 60, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Call three treants to fight at your side for 30 seconds.',
    execution: { kind: 'summon', ally: 'treant', count: 3, duration: 30 } },
  { id: 'savageRoar', name: 'Savage Roar', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', resource: 'energy', combo: 'spend', requiresForm: 'cat',
    description: 'Finishing move that increases your damage by 30% for 6 seconds per combo point spent. Cat Form only.',
    execution: { kind: 'comboStrike', spend: true, buffPerCombo: { duration: 6, stats: { damagePercent: 30 } } } },
  { id: 'shred', name: 'Shred', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 2.25, color: D, targetMode: 'enemy', resource: 'energy', combo: 'build', requiresForm: 'cat', requiresBehind: true,
    description: 'Shred your target from behind. Awards 1 combo point. Cat Form only.',
    execution: { kind: 'comboStrike', build: 1, requiresBehind: true } },
  { id: 'ravage', name: 'Ravage', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 2.6, color: D, targetMode: 'enemy', resource: 'energy', combo: 'build', requiresForm: 'cat', requiresStealth: true,
    description: 'Ravage your target from stealth. Awards 1 combo point. Cat Form only.',
    execution: { kind: 'comboStrike', build: 1, requiresStealth: true } },
  { id: 'tigersFury', name: 'Tiger\'s Fury', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, resource: 'energy', requiresForm: 'cat',
    description: 'Restore 60 energy and increase your damage by 15% for 6 seconds. Cat Form only.',
    execution: { kind: 'buff', buff: { duration: 6, stats: { damagePercent: 15 }, resourcePerSecond: 10 } } },
  { id: 'berserk', name: 'Berserk', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, requiresForm: 'cat',
    description: 'Enter a feral frenzy, increasing your damage by 25% and regenerating energy for 15 seconds. Cat Form only.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { damagePercent: 25 }, resourcePerSecond: 10 } } },
  { id: 'survivalInstincts', name: 'Survival Instincts', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, resource: 'rage', requiresForm: 'bear',
    description: 'Survival instincts reduce all damage taken by 30% for 20 seconds. Bear Form only.',
    execution: { kind: 'buff', buff: { duration: 20, reduction: 0.3 } } },
  { id: 'frenziedRegeneration', name: 'Frenzied Regeneration', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, resource: 'rage', requiresForm: 'bear',
    description: 'Convert rage into health, restoring 3% of your maximum health per second for 10 seconds. Bear Form only.',
    execution: { kind: 'buff', buff: { duration: 10, healPerSecond: 0.03 } } },
  { id: 'growl', name: 'Growl', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 10, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 420, resource: 'rage', requiresForm: 'bear',
    description: 'Growl at your target, forcing it to attack you for 3 seconds. Bear Form only.',
    execution: { kind: 'taunt', duration: 3 } },
  { id: 'challengingRoar', name: 'Challenging Roar', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 180, damageMultiplier: 0.2, color: D, resource: 'rage', requiresForm: 'bear',
    description: 'A challenging roar that strikes all nearby enemies, forcing them to engage you. Bear Form only.',
    execution: { kind: 'radial', radius: 140, melee: true, taunt: 3 } },
  { id: 'demoralizingRoar', name: 'Demoralizing Roar', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0.2, color: D, resource: 'rage', requiresForm: 'bear',
    description: 'A demoralizing roar that weakens all nearby enemies for 10 seconds. Bear Form only.',
    execution: { kind: 'radial', radius: 140, melee: true, slow: { duration: 10, factor: 0.85 } } },
  { id: 'lacerate', name: 'Lacerate', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 0, damageMultiplier: 0.8, color: D, targetMode: 'enemy', resource: 'rage', requiresForm: 'bear',
    description: 'Lacerate your target, causing it to bleed over 15 seconds. Bear Form only.',
    execution: { kind: 'strike', dot: { school: 'bleed', dpsMultiplier: 0.15, duration: 15 } } },
  { id: 'enrage', name: 'Enrage', classId: 'druid', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, resource: 'rage', requiresForm: 'bear',
    description: 'Enrage, generating 20 rage over 10 seconds. Bear Form only.',
    execution: { kind: 'buff', buff: { duration: 10, resourcePerSecond: 2 } } },
  { id: 'dash', name: 'Dash', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, requiresForm: 'cat',
    description: 'Dash, increasing your movement speed by 70% for 15 seconds. Cat Form only.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { moveSpeedPercent: 70 } } } },
  { id: 'aquaticForm', name: 'Aquatic Form', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into an aquatic form: +50% movement speed, but your strikes are weaker while transformed.',
    execution: { kind: 'form', form: 'travel', buff: { duration: 3600, exclusiveGroup: 'form', form: 'travel', stats: { moveSpeedPercent: 50, damagePercent: -10, spellDamagePercent: -10 } } } },
  { id: 'flightForm', name: 'Flight Form', classId: 'druid', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into flight form: +150% movement speed, but your strikes are much weaker while airborne.',
    execution: { kind: 'form', form: 'travel', buff: { duration: 3600, exclusiveGroup: 'form', form: 'travel', stats: { moveSpeedPercent: 150, damagePercent: -30, spellDamagePercent: -30 } } } },
  { id: 'treeOfLife', name: 'Tree of Life', classId: 'druid', requirement: 'any', domain: 'Arcana', tier: 'ultimate',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Shapeshift into the Tree of Life, regenerating health and empowering your healing magic.',
    execution: { kind: 'form', form: 'moonkin', buff: { duration: 3600, exclusiveGroup: 'form', form: 'moonkin', healPerSecond: 0.025, stats: { spellDamagePercent: 10 } } } },
]);
