import type { WowSkill } from './skill-execution-content.ts';

const W = '#C79C6E'; // warrior class color

/** Warrior kit — rage-fueled melee. Costs are rage (class resource). */
export const WARRIOR_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'heroicStrike', name: 'Heroic Strike', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 1.5, color: W, targetMode: 'enemy',
    description: 'A strong instant strike against your target.',
    execution: { kind: 'strike' } },
  { id: 'charge', name: 'Charge', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 15, damageMultiplier: 0.6, color: W, targetMode: 'enemy', range: 350,
    description: 'Rush your target, stunning it for 1 second and generating 10 rage.',
    execution: { kind: 'dash', duration: 0.3, speed: 900, radius: 24, stun: 1, toTarget: true, resourceGain: 10 } },
  { id: 'thunderClap', name: 'Thunder Clap', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 20, cooldown: 4, damageMultiplier: 1.1, color: W,
    description: 'Slam the ground, damaging and slowing nearby enemies.',
    execution: { kind: 'radial', radius: 110, melee: true, slow: { duration: 4, factor: 0.7 } } },
  { id: 'hamstring', name: 'Hamstring', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0.7, color: W, targetMode: 'enemy',
    description: 'Maim your target, slowing it by 40% for 5 seconds.',
    execution: { kind: 'strike', slow: { duration: 5, factor: 0.6 } } },
  { id: 'overpower', name: 'Overpower', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 5, cooldown: 5, damageMultiplier: 1.6, color: W, targetMode: 'enemy', requiresBuff: 'battleStance',
    description: 'A precise strike that cannot be avoided. Requires Battle Stance.',
    execution: { kind: 'strike' } },
  { id: 'execute', name: 'Execute', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 6, damageMultiplier: 2.8, color: W, targetMode: 'enemy', executeThreshold: 0.2,
    description: 'Finish a wounded enemy. Only usable below 20% health. 6 second cooldown.',
    execution: { kind: 'strike' } },
  { id: 'pummel', name: 'Pummel', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 10, cooldown: 10, damageMultiplier: 0.4, color: W, targetMode: 'enemy', requiresBuff: 'berserkerStance',
    description: 'Interrupt your target\'s attack, silencing it for 4 seconds. Requires Berserker Stance.',
    execution: { kind: 'interrupt', silence: 4 } },
  { id: 'sunderArmor', name: 'Sunder Armor', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0.5, color: W, targetMode: 'enemy',
    description: 'Crack your target\'s armor, increasing its damage taken by 10% for 15 seconds.',
    execution: { kind: 'strike', sunder: 0.1 } },
  { id: 'battleShout', name: 'Battle Shout', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'A war cry that increases your damage by 10% for 60 seconds.',
    execution: { kind: 'buff', buff: { duration: 60, stats: { damagePercent: 10, spellDamagePercent: 10 } } } },
  { id: 'berserkerRage', name: 'Berserker Rage', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true, requiresBuff: 'berserkerStance',
    description: 'Enter a rage: immune to fear and generate 5 rage per second for 10 seconds. Requires Berserker Stance.',
    execution: { kind: 'buff', buff: { duration: 10, resourcePerSecond: 5, breakControl: true } } },
  { id: 'shieldSlam', name: 'Shield Slam', classId: 'warrior', requirement: 'shield', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 6, damageMultiplier: 1.9, color: W, targetMode: 'enemy',
    description: 'Slam your target with your shield.',
    execution: { kind: 'strike' } },
  { id: 'shieldBlock', name: 'Shield Block', classId: 'warrior', requirement: 'shield', domain: 'Might', tier: 'advanced',
    manaCost: 10, cooldown: 10, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true, requiresBuff: 'defensiveStance',
    description: 'Raise your shield, blocking all incoming hits for 3 seconds. Requires Defensive Stance.',
    execution: { kind: 'guard', duration: 3, reduction: 0.75 } },
  { id: 'revenge', name: 'Revenge', classId: 'warrior', requirement: 'shield', domain: 'Might', tier: 'basic',
    manaCost: 5, cooldown: 5, damageMultiplier: 1.4, color: W, targetMode: 'enemy', requiresBuff: 'defensiveStance',
    description: 'Counterstrike your target with shield and blade. Requires Defensive Stance.',
    execution: { kind: 'strike' } },
  { id: 'shieldWall', name: 'Shield Wall', classId: 'warrior', requirement: 'shield', domain: 'Might', tier: 'ultimate',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true, requiresBuff: 'defensiveStance',
    description: 'Reduce all damage taken by 60% for 8 seconds. Requires Defensive Stance.',
    execution: { kind: 'buff', buff: { duration: 8, reduction: 0.6 } } },
  { id: 'mortalStrike', name: 'Mortal Strike', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 25, cooldown: 6, damageMultiplier: 2.0, color: W, targetMode: 'enemy',
    description: 'A vicious strike that leaves a bleeding wound.',
    execution: { kind: 'strike', dot: { school: 'bleed', dpsMultiplier: 0.15, duration: 6 } } },
  { id: 'bloodthirst', name: 'Bloodthirst', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 4, damageMultiplier: 1.7, color: W, targetMode: 'enemy',
    description: 'A savage strike that restores health equal to 30% of the damage dealt.',
    execution: { kind: 'strike', healFrac: 0.3 } },
  { id: 'bladestorm', name: 'Bladestorm', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'ultimate',
    manaCost: 30, cooldown: 60, damageMultiplier: 1.2, color: W, channel: { duration: 4, ticks: 6 },
    description: 'Become a whirling storm of steel, striking all nearby enemies for 4 seconds.',
    execution: { kind: 'channel', school: 'physical', ticks: 6, duration: 4, radius: 120 } },
  { id: 'heroicLeap', name: 'Heroic Leap', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 1.0, color: W, targetMode: 'point', range: 420,
    description: 'Leap to your aim, damaging enemies where you land.',
    execution: { kind: 'dash', duration: 0.35, speed: 800, radius: 60, stun: 0.5 } },
  { id: 'intimidatingShout', name: 'Intimidating Shout', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 90, damageMultiplier: 0, color: W,
    description: 'A terrifying roar that fears nearby enemies for 4 seconds.',
    execution: { kind: 'cc', cc: 'fear', duration: 4, radius: 120, maxTargets: 5 } },
  { id: 'sweepingStrikes', name: 'Sweeping Strikes', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Your strikes hit with greater force for 12 seconds (+10% damage).',
    execution: { kind: 'buff', buff: { duration: 12, stats: { damagePercent: 10 } } } },
  { id: 'slam', name: 'Slam', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 2.2, color: W, targetMode: 'enemy', castTime: 1.5,
    description: 'A wind-up strike that deals heavy weapon damage.',
    execution: { kind: 'strike' } },
  { id: 'rend', name: 'Rend', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 1.0, color: W, targetMode: 'enemy',
    description: 'Open a bleeding wound that drains the target for 15 seconds.',
    execution: { kind: 'dot', dot: { school: 'bleed', dpsMultiplier: 0.25, duration: 15 } } },
  { id: 'victoryRush', name: 'Victory Rush', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 15, damageMultiplier: 1.5, color: W, targetMode: 'enemy',
    description: 'A triumphant strike that restores health equal to the damage dealt. Best used after a kill.',
    execution: { kind: 'strike', healFrac: 1.0 } },
  { id: 'intercept', name: 'Intercept', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 10, cooldown: 30, damageMultiplier: 0.5, color: W, targetMode: 'enemy', range: 350, requiresBuff: 'berserkerStance',
    description: 'Charge an enemy, stunning it for 2 seconds. Requires Berserker Stance.',
    execution: { kind: 'dash', duration: 0.3, speed: 900, radius: 24, stun: 2, toTarget: true } },
  { id: 'intervene', name: 'Intervene', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 10, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'point', range: 350,
    description: 'Rush to an ally\'s aid at high speed.',
    execution: { kind: 'dash', duration: 0.3, speed: 900, radius: 24 } },
  { id: 'spellReflection', name: 'Spell Reflection', classId: 'warrior', requirement: 'shield', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 10, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true, requiresBuff: 'defensiveStance',
    description: 'Raise your shield to reflect the next spell cast at you for 5 seconds. Requires Defensive Stance.',
    execution: { kind: 'buff', buff: { duration: 5, reflect: 1 } } },
  { id: 'disarm', name: 'Disarm', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 60, damageMultiplier: 0.5, color: W, targetMode: 'enemy', requiresBuff: 'defensiveStance',
    description: 'Strike your target\'s weapon away, increasing its damage taken by 15% for 10 seconds. Requires Defensive Stance.',
    execution: { kind: 'strike', sunder: 0.15 } },
  { id: 'demoralizingShout', name: 'Demoralizing Shout', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0, color: W,
    description: 'A demoralizing roar that weakens nearby enemies, increasing their damage taken by 10% for 15 seconds.',
    execution: { kind: 'radial', radius: 140, melee: false, sunder: 0.1 } },
  { id: 'piercingHowl', name: 'Piercing Howl', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0, color: W,
    description: 'A piercing howl that slows all nearby enemies by 50% for 6 seconds.',
    execution: { kind: 'radial', radius: 140, melee: false, slow: { duration: 6, factor: 0.5 } } },
  { id: 'concussionBlow', name: 'Concussion Blow', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 15, cooldown: 30, damageMultiplier: 0.75, color: W, targetMode: 'enemy',
    description: 'A brutal blow to the head that stuns the target for 4 seconds.',
    execution: { kind: 'strike', stun: 4 } },
  { id: 'shockwave', name: 'Shockwave', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'ultimate',
    manaCost: 15, cooldown: 20, damageMultiplier: 0.75, color: W,
    description: 'Slam the ground, sending a shockwave that damages and stuns enemies before you for 4 seconds.',
    execution: { kind: 'cone', radius: 140, arc: Math.PI * 0.7, stun: 4 } },
  { id: 'lastStand', name: 'Last Stand', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Dig deep, increasing your maximum health by 30% for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, stats: { maxHpPercent: 30 } } } },
  { id: 'enragedRegeneration', name: 'Enraged Regeneration', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 15, cooldown: 180, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Channel your rage into regeneration, restoring 3% of maximum health per second for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, healPerSecond: 0.03 } } },
  { id: 'commandingShout', name: 'Commanding Shout', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'A commanding war cry that increases your maximum health by 15% for 2 minutes.',
    execution: { kind: 'buff', buff: { duration: 120, stats: { maxHpPercent: 15 } } } },
  { id: 'taunt', name: 'Taunt', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 10, damageMultiplier: 0, color: W, targetMode: 'enemy', range: 420,
    description: 'Taunt the target, forcing it to attack you for 3 seconds.',
    execution: { kind: 'taunt', duration: 3 } },
  { id: 'challengingShout', name: 'Challenging Shout', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 5, cooldown: 180, damageMultiplier: 0.3, color: W,
    description: 'A challenging roar that provokes all nearby enemies to attack you.',
    execution: { kind: 'radial', radius: 140, melee: false, taunt: 3 } },
  { id: 'heroicThrow', name: 'Heroic Throw', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 1.2, color: W, targetMode: 'enemy', range: 420,
    description: 'Hurl your weapon at the target, dealing heavy damage.',
    execution: { kind: 'projectile', speed: 700, radius: 6, offsets: [0], effects: { style: 'arrow' } } },
  { id: 'shatteringThrow', name: 'Shattering Throw', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 25, cooldown: 300, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Hurl your weapon at the target, shattering its armor and increasing damage taken by 20% for 10 seconds.',
    execution: { kind: 'projectile', speed: 700, radius: 6, offsets: [0], effects: { style: 'arrow' }, sunder: 0.2 } },
  { id: 'retaliation', name: 'Retaliation', classId: 'warrior', requirement: 'melee', domain: 'Might', tier: 'ultimate',
    manaCost: 0, cooldown: 300, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Instantly counterattack any enemy that strikes you in melee for 12 seconds.',
    execution: { kind: 'buff', buff: { duration: 12, reflect: 1 } } },
  { id: 'battleStance', name: 'Battle Stance', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'A balanced combat stance: +5% damage dealt. Enables Overpower.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'stance', stats: { damagePercent: 5 } } } },
  { id: 'defensiveStance', name: 'Defensive Stance', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'A guarded stance: +40 armor, +40 maximum life and 10% less damage taken. Enables Revenge, Shield Block, Shield Wall, Disarm and Spell Reflection.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'stance', reduction: 0.1, stats: { armor: 40, maxHp: 40 } } } },
  { id: 'berserkerStance', name: 'Berserker Stance', classId: 'warrior', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'A reckless stance: +3% critical chance and +8% damage dealt. Enables Pummel, Intercept and Berserker Rage.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'stance', stats: { critChance: 3, damagePercent: 8 } } } },
]);
