import type { WowSkill } from './skill-execution-content.ts';

const H = '#ABD473'; // hunter class color

/** Hunter kit — mana-fueled ranged shots and beast utility. Costs are mana (class resource). */
export const HUNTER_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'arcaneShot', name: 'Arcane Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 25, cooldown: 6, damageMultiplier: 1.3, color: H, targetMode: 'enemy', range: 490,
    description: 'An instant shot that deals arcane damage to your target.',
    execution: { kind: 'strike', school: 'arcane' } },
  { id: 'aimedShot', name: 'Aimed Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 8, damageMultiplier: 2.5, color: H, targetMode: 'enemy', range: 490, castTime: 2,
    description: 'Take careful aim and fire a devastating shot after a 2 second cast.',
    execution: { kind: 'strike' } },
  { id: 'multiShot', name: 'Multi-Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 40, cooldown: 6, damageMultiplier: 0.9, color: H, targetMode: 'enemy', range: 490,
    description: 'Fire a volley of three arrows in a spreading fan.',
    execution: { kind: 'projectile', speed: 620, radius: 4, offsets: [-0.22, 0, 0.22], effects: { style: 'arrow' } } },
  { id: 'serpentSting', name: 'Serpent Sting', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0.4, color: H, targetMode: 'enemy', range: 490,
    description: 'Sting your target with venom, dealing nature damage over 15 seconds.',
    execution: { kind: 'dot', dot: { school: 'nature', dpsMultiplier: 0.25, duration: 15 } } },
  { id: 'concussiveShot', name: 'Concussive Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 20, cooldown: 12, damageMultiplier: 0.5, color: H, targetMode: 'enemy', range: 490,
    description: 'Daze your target, slowing it by 50% for 4 seconds.',
    execution: { kind: 'strike', slow: { duration: 4, factor: 0.5 } } },
  { id: 'scatterShot', name: 'Scatter Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 30, damageMultiplier: 0.5, color: H, targetMode: 'enemy', range: 280,
    description: 'A short-range blast that incapacitates your target for 3 seconds. Any damage breaks the effect.',
    execution: { kind: 'strike', cc: { kind: 'incapacitate', duration: 3 } } },
  { id: 'freezingTrap', name: 'Freezing Trap', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 30, damageMultiplier: 0, color: H, targetMode: 'point', range: 350,
    description: 'Hurl a freezing trap at the target point, freezing the nearest enemy for 6 seconds.',
    execution: { kind: 'cc', cc: 'freeze', duration: 6, radius: 60, maxTargets: 1 } },
  { id: 'disengage', name: 'Disengage', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 15, cooldown: 25, damageMultiplier: 0, color: H,
    description: 'Leap backward, escaping melee range.',
    execution: { kind: 'step', duration: 0.25, speed: 520, retreat: true } },
  { id: 'aspectHawk', name: 'Aspect of the Hawk', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the aspect of a hawk, increasing your ranged damage by 15%. Only one aspect can be active.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', stats: { damagePercent: 15 } } } },
  { id: 'feignDeath', name: 'Feign Death', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Play dead, dropping all enemy aggro for 4 seconds.',
    execution: { kind: 'stealth', duration: 4, dropAggro: true } },
  { id: 'callPet', name: 'Call Pet', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 35, cooldown: 10, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Call your loyal wolf companion to fight at your side.',
    execution: { kind: 'summon', ally: 'wolf', count: 1 } },
  { id: 'killCommand', name: 'Kill Command', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 45, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Command your pet to strike with fury: your pet deals 50% more damage and you deal 25% more damage for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stats: { damagePercent: 25 }, allyDamage: 0.5 } } },
  { id: 'bestialWrath', name: 'Bestial Wrath', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 10, cooldown: 90, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Send your pet into a rage: your pet deals 50% more damage and you deal 30% more damage for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stats: { damagePercent: 30 }, allyDamage: 0.5 } } },
  { id: 'huntersVolley', name: 'Hunter\'s Volley', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'ultimate',
    manaCost: 40, cooldown: 30, damageMultiplier: 0.6, color: H, targetMode: 'point', range: 420, channel: { duration: 4, ticks: 8 },
    description: 'Channel a rain of arrows over the target area for 4 seconds.',
    execution: { kind: 'channel', school: 'physical', ticks: 8, duration: 4, radius: 140, targetRange: 420 } },
  { id: 'explosiveShot', name: 'Explosive Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 6, damageMultiplier: 1.4, color: H, targetMode: 'enemy', range: 490,
    description: 'Fire an explosive charge that detonates on impact, burning nearby enemies.',
    execution: { kind: 'projectile', speed: 560, radius: 5, offsets: [0], effects: { style: 'fire', blastRadius: 70 } } },
  { id: 'steadyShot', name: 'Steady Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 1.6, color: H, targetMode: 'enemy', range: 490, castTime: 1.5,
    description: 'A steady shot that builds pressure between cooldowns.',
    execution: { kind: 'strike' } },
  { id: 'killShot', name: 'Kill Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 15, damageMultiplier: 2.4, color: H, targetMode: 'enemy', range: 490, executeThreshold: 0.2,
    description: 'Finish a wounded enemy. Only usable below 20% health.',
    execution: { kind: 'strike' } },
  { id: 'chimeraShot', name: 'Chimera Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'ultimate',
    manaCost: 40, cooldown: 10, damageMultiplier: 1.6, color: H, targetMode: 'enemy', range: 490,
    description: 'A shot that consumes your Serpent Sting, instantly dealing 40% of its remaining nature damage.',
    execution: { kind: 'strike', consumeDot: { school: 'nature', multiplier: 0.4 } } },
  { id: 'raptorStrike', name: 'Raptor Strike', classId: 'hunter', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 6, damageMultiplier: 1.5, color: H, targetMode: 'enemy', range: 70,
    description: 'A vicious melee strike that deals heavy damage to your target.',
    execution: { kind: 'strike' } },
  { id: 'mongooseBite', name: 'Mongoose Bite', classId: 'hunter', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 10, cooldown: 5, damageMultiplier: 1.4, color: H, targetMode: 'enemy', range: 70,
    description: 'Counterattack your enemy with a savage bite, dealing damage.',
    execution: { kind: 'strike' } },
  { id: 'wingClip', name: 'Wing Clip', classId: 'hunter', requirement: 'melee', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0.5, color: H, targetMode: 'enemy', range: 70,
    description: 'Maim your target, slowing its movement speed by 50% for 10 seconds.',
    execution: { kind: 'strike', slow: { duration: 10, factor: 0.5 } } },
  { id: 'frostTrap', name: 'Frost Trap', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 30, damageMultiplier: 0, color: H, targetMode: 'point', range: 350,
    description: 'Place a frost trap that creates an icy slick, slowing all enemies within it by 50%.',
    execution: { kind: 'ground', effect: 'frost', radius: 120, delay: 1, duration: 30, interval: 1, style: 'frost', slow: { duration: 3, factor: 0.5 } } },
  { id: 'immolationTrap', name: 'Immolation Trap', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 25, cooldown: 30, damageMultiplier: 0.8, color: H, targetMode: 'point', range: 350,
    description: 'Hurl a fire trap at the target point; it arms for a second, then detonates, burning enemies caught in the blast over 15 seconds.',
    execution: { kind: 'ground', effect: 'meteor', radius: 80, delay: 1, duration: 0, interval: 1, style: 'fire', burn: { duration: 15, damageMultiplier: 0.15 } } },
  { id: 'explosiveTrap', name: 'Explosive Trap', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 30, cooldown: 30, damageMultiplier: 1.2, color: H, targetMode: 'point', range: 350,
    description: 'Hurl an explosive trap at the target point; it arms for a second, then detonates, burning all nearby enemies.',
    execution: { kind: 'ground', effect: 'meteor', radius: 110, delay: 1, duration: 0, interval: 1, style: 'fire', burn: { duration: 8, damageMultiplier: 0.2 } } },
  { id: 'deterrence', name: 'Deterrence', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 10, cooldown: 90, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Deflect attacks and spells, reducing damage taken by 90% for 5 seconds.',
    execution: { kind: 'buff', buff: { duration: 5, reduction: 0.9 } } },
  { id: 'misdirection', name: 'Misdirection', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 30, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Your pet intercepts half the damage you take for 30 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, petShare: 0.5 } } },
  { id: 'tranquilizingShot', name: 'Tranquilizing Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 8, damageMultiplier: 0.3, color: H, targetMode: 'enemy', range: 490,
    description: 'A soothing shot that calms your target, slowing it by 50% for 4 seconds.',
    execution: { kind: 'projectile', speed: 640, radius: 4, offsets: [0], effects: { style: 'spirit', slowFactor: 0.5, slowDuration: 4 } } },
  { id: 'viperSting', name: 'Viper Sting', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 15, damageMultiplier: 0.4, color: H, targetMode: 'enemy', range: 490,
    description: 'Sting your target, draining its vitality as nature damage over 8 seconds.',
    execution: { kind: 'projectile', speed: 600, radius: 4, offsets: [0], effects: { style: 'nature' }, dot: { school: 'nature', dpsMultiplier: 0.2, duration: 8 } } },
  { id: 'scorpidSting', name: 'Scorpid Sting', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0.3, color: H, targetMode: 'enemy', range: 490,
    description: 'Sting your target with scorpid venom, dealing nature damage over 20 seconds.',
    execution: { kind: 'projectile', speed: 600, radius: 4, offsets: [0], effects: { style: 'nature' }, dot: { school: 'nature', dpsMultiplier: 0.15, duration: 20 } } },
  { id: 'mendPet', name: 'Mend Pet', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self',
    description: 'Mend your pet\'s wounds, healing it over 15 seconds.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.15, hotFrac: 0.03, hot: { duration: 15, interval: 1 }, pet: 'mend' } },
  { id: 'revivePet', name: 'Revive Pet', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 80, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', castTime: 6,
    description: 'Revive your fallen pet, returning it to life with full health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 1, pet: 'revive' } },
  { id: 'tameBeast', name: 'Tame Beast', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'enemy', range: 300, castTime: 20,
    description: 'Channel a bond with a wild beast for 20 seconds, taming it into your companion.',
    execution: { kind: 'tame' } },
  { id: 'intimidation', name: 'Intimidation', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'advanced',
    manaCost: 15, cooldown: 60, damageMultiplier: 0, color: H, targetMode: 'enemy', range: 490,
    description: 'Unleash an intimidating presence, incapacitating the target for 3 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 3 } },
  { id: 'wyvernSting', name: 'Wyvern Sting', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'ultimate',
    manaCost: 30, cooldown: 60, damageMultiplier: 0.3, color: H, targetMode: 'enemy', range: 490,
    description: 'A stinging shot that freezes your target for 6 seconds while venom eats at it.',
    execution: { kind: 'projectile', speed: 560, radius: 5, offsets: [0], effects: { style: 'nature' }, cc: { kind: 'freeze', duration: 6 }, dot: { school: 'nature', dpsMultiplier: 0.2, duration: 6 } } },
  { id: 'blackArrow', name: 'Black Arrow', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'ultimate',
    manaCost: 25, cooldown: 30, damageMultiplier: 0.6, color: H, targetMode: 'enemy', range: 490,
    description: 'Fire a black arrow that deals shadow damage over 15 seconds and increases your damage against the target.',
    execution: { kind: 'projectile', speed: 600, radius: 5, offsets: [0], effects: { style: 'shadow' }, dot: { school: 'shadow', dpsMultiplier: 0.3, duration: 15 } } },
  { id: 'silencingShot', name: 'Silencing Shot', classId: 'hunter', requirement: 'bow', domain: 'Cunning', tier: 'advanced',
    manaCost: 20, cooldown: 20, damageMultiplier: 0.5, color: H, targetMode: 'enemy', range: 490,
    description: 'A shot that interrupts spellcasting and silences your target for 3 seconds.',
    execution: { kind: 'interrupt', silence: 3 } },
  { id: 'readiness', name: 'Focus', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'ultimate',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Steady your focus, restoring 10 mana per second for 5 seconds.',
    execution: { kind: 'buff', buff: { duration: 5, resourcePerSecond: 10 } } },
  { id: 'aspectViper', name: 'Aspect of the Viper', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the aspect of the viper, regenerating 2% of your maximum mana per second.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', manaPerSecond: 0.02 } } },
  { id: 'aspectCheetah', name: 'Aspect of the Cheetah', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the aspect of the cheetah, moving 30% faster.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', stats: { moveSpeedPercent: 30 } } } },
  { id: 'aspectPack', name: 'Aspect of the Pack', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the pack\'s aspect, moving 30% faster.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', stats: { moveSpeedPercent: 30 } } } },
  { id: 'aspectDragonhawk', name: 'Aspect of the Dragonhawk', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the aspect of the dragonhawk: +10% damage dealt and +5% critical chance.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', stats: { damagePercent: 10, critChance: 5 } } } },
  { id: 'aspectBeast', name: 'Aspect of the Beast', classId: 'hunter', requirement: 'any', domain: 'Cunning', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: H, targetMode: 'self', offGcd: true,
    description: 'Take on the aspect of the beast: +5% damage dealt and +10% movement speed.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'aspect', stats: { damagePercent: 5, moveSpeedPercent: 10 } } } },
]);
