import type { WowSkill } from './skill-execution-content.ts';

const W = '#9482C9'; // warlock class color

/** Warlock kit — shadow bolts, curses and demons. Costs are mana; shardCost spends soul shards. */
export const WARLOCK_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'shadowBolt', name: 'Shadow Bolt', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 1.8, color: W, targetMode: 'enemy', range: 420, castTime: 1.7,
    description: 'Hurl a bolt of shadow at your target.',
    execution: { kind: 'projectile', speed: 700, radius: 10, offsets: [0], effects: { style: 'shadow' } } },
  { id: 'immolate', name: 'Immolate', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.9, color: W, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Ignite your target, dealing fire damage plus further damage over 12 seconds.',
    execution: { kind: 'strike', school: 'fire', dot: { school: 'fire', dpsMultiplier: 0.12, duration: 12 } } },
  { id: 'corruption', name: 'Corruption', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420,
    description: 'Corrupt your target, dealing shadow damage over 15 seconds.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.18, duration: 15 } } },
  { id: 'curseOfAgony', name: 'Curse of Agony', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420,
    description: 'Curse your target with escalating agony, dealing shadow damage over 20 seconds.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.1, duration: 20, ramp: 0.1 } } },
  { id: 'unstableAffliction', name: 'Unstable Affliction', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Afflict your target with volatile shadow energy, dealing heavy damage over 12 seconds.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.3, duration: 12 } } },
  { id: 'drainLife', name: 'Drain Life', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0.5, color: W, targetMode: 'enemy', range: 280,
    channel: { duration: 4, ticks: 4 },
    description: 'Channel shadow for 4 seconds, draining life from your target to heal yourself.',
    execution: { kind: 'channel', school: 'shadow', ticks: 4, duration: 4, healFrac: 1 } },
  { id: 'drainSoul', name: 'Drain Soul', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.5, color: W, targetMode: 'enemy', range: 280, executeThreshold: 0.25,
    channel: { duration: 6, ticks: 4 },
    description: 'Channel shadow for 6 seconds, dealing triple damage. Only usable on targets below 25% health.',
    execution: { kind: 'channel', school: 'shadow', ticks: 4, duration: 6, executeBonus: 2 } },
  { id: 'searingPain', name: 'Searing Pain', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 1.4, color: W, targetMode: 'enemy', range: 420,
    description: 'Sear your target with agonizing fire.',
    execution: { kind: 'strike', school: 'fire' } },
  { id: 'shadowburn', name: 'Shadowburn', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 15, damageMultiplier: 1.9, color: W, targetMode: 'enemy', range: 420, executeThreshold: 0.2, shardCost: 1,
    description: 'Spend a soul shard to blast your target with shadow. Only usable below 20% health.',
    execution: { kind: 'strike', school: 'shadow' } },
  { id: 'chaosBolt', name: 'Chaos Bolt', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 12, damageMultiplier: 2.6, color: W, targetMode: 'enemy', range: 420, castTime: 2,
    description: 'Hurl a massive bolt of chaotic fire at your target.',
    execution: { kind: 'projectile', speed: 700, radius: 12, offsets: [0], effects: { style: 'fire' } } },
  { id: 'conflagrate', name: 'Conflagrate', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 10, damageMultiplier: 1.2, color: W, targetMode: 'enemy', range: 420,
    description: 'Consume your Immolate on the target, bursting its remaining burn damage instantly.',
    execution: { kind: 'strike', school: 'fire', consumeDot: { school: 'fire', multiplier: 0.6 } } },
  { id: 'fear', name: 'Fear', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 15, damageMultiplier: 0, color: W, targetMode: 'enemy', range: 280, castTime: 1.5,
    description: 'Strike terror into your target, causing it to flee for 5 seconds.',
    execution: { kind: 'cc', cc: 'fear', duration: 5 } },
  { id: 'howlOfTerror', name: 'Howl of Terror', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 40, damageMultiplier: 0, color: W,
    description: 'A bloodcurdling howl that fears nearby enemies for 4 seconds.',
    execution: { kind: 'cc', cc: 'fear', duration: 4, radius: 120, maxTargets: 5 } },
  { id: 'warlockDeathCoil', name: 'Death Coil', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 120, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 280,
    description: 'Horrify your target for 2 seconds and restore health equal to 30% of the damage dealt.',
    execution: { kind: 'strike', school: 'shadow', stun: 2, healFrac: 0.3 } },
  { id: 'lifeTap', name: 'Life Tap', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self',
    description: 'Sacrifice your own health to restore 12% of your mana.',
    execution: { kind: 'cleanse', hpCost: 0.15, resourceGainFrac: 0.12 } },
  { id: 'felArmor', name: 'Fel Armor', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Demonic armor increases your armor and spell power and regenerates health for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, exclusiveGroup: 'armor', stats: { armorPercent: 20, spellDamagePercent: 10 }, healPerSecond: 0.01 } } },
  { id: 'summonImp', name: 'Summon Imp', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 3,
    description: 'Summon an imp to fight at your side until dismissed or slain.',
    execution: { kind: 'summon', ally: 'imp', count: 1 } },
  { id: 'summonFelguard', name: 'Summon Felguard', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 80, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to summon a felguard to fight at your side until dismissed or slain.',
    execution: { kind: 'summon', ally: 'felguard', count: 1 } },
  { id: 'metamorphosis', name: 'Metamorphosis', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 50, cooldown: 120, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Transform into a demon, increasing all damage dealt by 20% for 30 seconds.',
    execution: { kind: 'form', form: 'metamorph', buff: { duration: 30, exclusiveGroup: 'form', form: 'metamorph', stats: { damagePercent: 20, spellDamagePercent: 20 } } } },
  { id: 'seedOfCorruption', name: 'Seed of Corruption', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 0, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Plant a seed of corruption that festers for 10 seconds; if the host dies early, it detonates for half its remaining damage onto nearby enemies.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.15, duration: 10, detonate: 0.5 } } },
  { id: 'rainOfFire', name: 'Rain of Fire', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 0, damageMultiplier: 0.8, color: W, targetMode: 'point', range: 420,
    description: 'Rain fire over the target area for 6 seconds.',
    execution: { kind: 'ground', effect: 'storm', radius: 120, delay: 0.3, duration: 6, interval: 1, style: 'fire' } },
  { id: 'shadowfury', name: 'Shadowfury', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 20, damageMultiplier: 0.6, color: W, targetMode: 'point', range: 420, castTime: 0.5,
    description: 'Unleash shadowfury at the target point, stunning enemies for 2 seconds.',
    execution: { kind: 'cc', cc: 'stun', duration: 2, radius: 80 } },
  { id: 'curseOfElements', name: 'Curse of the Elements', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.5, color: W, targetMode: 'enemy', range: 420,
    description: 'Curse your target, weakening its defenses so it takes increased damage.',
    execution: { kind: 'strike', school: 'shadow', sunder: 0.13 } },
  { id: 'curseOfWeakness', name: 'Curse of Weakness', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.4, color: W, targetMode: 'enemy', range: 420,
    description: 'Curse your target, sapping its strength and slowing its attacks.',
    execution: { kind: 'strike', school: 'shadow', slow: { duration: 10, factor: 0.8 } } },
  { id: 'curseOfTongues', name: 'Curse of Tongues', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'enemy', range: 420,
    description: 'Curse your target to speak in demonic tongues, slowing its casting for 12 seconds.',
    execution: { kind: 'cc', cc: 'slow', duration: 12 } },
  { id: 'curseOfDoom', name: 'Curse of Doom', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 60, damageMultiplier: 1.0, color: W, targetMode: 'enemy', range: 420,
    description: 'Doom your target, dealing massive shadow damage after 60 seconds.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.6, duration: 60, interval: 60, detonate: 0.5 } } },
  { id: 'demonArmor', name: 'Demon Armor', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Demonic armor increases your armor and shadow resistance for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, exclusiveGroup: 'armor', stats: { armorPercent: 30, shadowResistance: 10 } } } },
  { id: 'demonicCircle', name: 'Demonic Circle: Teleport', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'self',
    description: 'Teleport back to your demonic circle.',
    execution: { kind: 'step', duration: 0.25, speed: 1400 } },
  { id: 'demonicEmpowerment', name: 'Demonic Empowerment', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Empower your demon, increasing its damage by 50% for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, allyDamage: 0.5 } } },
  { id: 'felDomination', name: 'Fel Domination', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 180, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Dominate the summoning ritual, greatly hastening your casting for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { castSpeedPercent: 50 } } } },
  { id: 'soulLink', name: 'Soul Link', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Link your soul to your demon: damage taken is reduced and 20% is redirected to it for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, reduction: 0.15, petShare: 0.2 } } },
  { id: 'darkPact', name: 'Dark Pact', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'self', requiresAlly: 'demon',
    description: 'Drain mana from your summoned demon, restoring 30% of your maximum mana.',
    execution: { kind: 'cleanse', resourceGainFrac: 0.3 } },
  { id: 'soulshatter', name: 'Soulshatter', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true, shardCost: 1,
    description: 'Spend a soul shard to shatter your threat, dropping all enemy aggro.',
    execution: { kind: 'stealth', duration: 3, dropAggro: true } },
  { id: 'ritualOfSouls', name: 'Ritual of Souls', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 300, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to perform a ritual that bolsters your vitality for 5 minutes.',
    execution: { kind: 'buff', buff: { duration: 300, stats: { maxHp: 25 } } } },
  { id: 'ritualOfSummoning', name: 'Ritual of Summoning', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 300, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to open a portal that calls a demonic ally for 60 seconds.',
    execution: { kind: 'summon', ally: 'imp', count: 1, duration: 60 } },
  { id: 'summonVoidwalker', name: 'Summon Voidwalker', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to summon a voidwalker to fight at your side until dismissed or slain.',
    execution: { kind: 'summon', ally: 'voidwalker', count: 1 } },
  { id: 'summonSuccubus', name: 'Summon Succubus', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to summon a succubus to fight at your side until dismissed or slain.',
    execution: { kind: 'summon', ally: 'succubus', count: 1 } },
  { id: 'summonFelhunter', name: 'Summon Felhunter', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to summon a felhunter to fight at your side until dismissed or slain.',
    execution: { kind: 'summon', ally: 'felhunter', count: 1 } },
  { id: 'summonDoomguard', name: 'Summon Doomguard', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 80, cooldown: 600, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 5, shardCost: 1,
    description: 'Spend a soul shard to summon a doomguard to fight for you for 5 minutes.',
    execution: { kind: 'summon', ally: 'doomguard', count: 1, duration: 300 } },
  { id: 'inferno', name: 'Inferno', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 80, cooldown: 600, damageMultiplier: 0, color: W, targetMode: 'point', range: 420, shardCost: 1,
    description: 'Spend a soul shard to instantly call an infernal down from the sky, stunning enemies where it lands. It fights for you for 60 seconds.',
    execution: { kind: 'summon', ally: 'infernal', count: 1, duration: 60, stun: 2, radius: 90 } },
  { id: 'banish', name: 'Banish', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Banish a demon or elemental, incapacitating it for 20 seconds. Damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 20 } },
  { id: 'enslaveDemon', name: 'Enslave Demon', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 30, damageMultiplier: 0, color: W, targetMode: 'enemy', range: 420, castTime: 2,
    description: 'Enslave a demon, binding it to your will for 15 seconds.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 15 } },
  { id: 'healthstone', name: 'Healthstone', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: W, targetMode: 'self', offGcd: true,
    description: 'Consume a healthstone to restore 25% of your health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.25 } },
  { id: 'soulstone', name: 'Soulstone', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 50, cooldown: 600, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 3, shardCost: 1,
    description: 'Spend a soul shard to store your soul, warding you against death for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, absorb: 0.15 } } },
  { id: 'createSpellstone', name: 'Create Spellstone', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 3,
    description: 'Create a spellstone that imbues your weapon with shadow damage and critical chance for 1 hour.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'weaponStone', imbue: { element: 'shadow', fraction: 0.15 }, stats: { critChance: 1 } } } },
  { id: 'createFirestone', name: 'Create Firestone', classId: 'warlock', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 0, color: W, targetMode: 'self', castTime: 3,
    description: 'Create a firestone that imbues your weapon with fire damage for 1 hour.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'weaponStone', imbue: { element: 'fire', fraction: 0.15 }, stats: { spellDamagePercent: 3 } } } },
]);
