import type { WowSkill } from './skill-execution-content.ts';

const M = '#69CCF0'; // mage class color

/** Mage kit — mana-fueled caster. Costs are mana (class resource). */
export const MAGE_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'frostbolt', name: 'Frostbolt', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 1.6, color: M, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Launch a bolt of frost that damages your target and slows it by 40% for 4 seconds.',
    execution: { kind: 'projectile', speed: 600, radius: 10, offsets: [0], effects: { style: 'frost', slowFactor: 0.6, slowDuration: 4 } } },
  { id: 'pyroblast', name: 'Pyroblast', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 3.2, color: M, targetMode: 'enemy', range: 420, castTime: 3,
    description: 'Hurl a massive fiery boulder that ignites your target, burning it over time.',
    execution: { kind: 'projectile', speed: 500, radius: 14, offsets: [0], effects: { style: 'fire', burnDuration: 4, burnDamageMultiplier: 0.3 } } },
  { id: 'fireBlast', name: 'Fire Blast', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 8, damageMultiplier: 1.2, color: M, targetMode: 'enemy', range: 280,
    description: 'Blast your target with an instant burst of flame.',
    execution: { kind: 'strike', school: 'fire' } },
  { id: 'scorch', name: 'Scorch', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 1.0, color: M, targetMode: 'enemy', range: 420, castTime: 1,
    description: 'A quick burst of fire that sears your target.',
    execution: { kind: 'strike', school: 'fire' } },
  { id: 'arcaneMissiles', name: 'Arcane Missiles', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 0, damageMultiplier: 0.7, color: M, targetMode: 'enemy', range: 420,
    channel: { duration: 3, ticks: 5 },
    description: 'Channel a barrage of arcane missiles, striking your target 5 times over 3 seconds.',
    execution: { kind: 'channel', school: 'arcane', ticks: 5, duration: 3 } },
  { id: 'arcaneExplosion', name: 'Arcane Explosion', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 1.0, color: M,
    description: 'Detonate an arcane burst, damaging all nearby enemies.',
    execution: { kind: 'radial', radius: 110, melee: false, style: 'arcane' } },
  { id: 'frostNova', name: 'Frost Nova', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 35, cooldown: 20, damageMultiplier: 0.3, color: M,
    description: 'Freeze nearby enemies solid for 5 seconds, marking them frozen for Shatter.',
    execution: { kind: 'cc', cc: 'freeze', duration: 5, radius: 120 } },
  { id: 'iceLance', name: 'Ice Lance', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 10, cooldown: 0, damageMultiplier: 0.8, color: M, targetMode: 'enemy', range: 420,
    description: 'Hurl a shard of ice, dealing triple damage against frozen targets.',
    execution: { kind: 'strike', school: 'frost', bonusVsFrozen: 3 } },
  { id: 'coneOfCold', name: 'Cone of Cold', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 10, damageMultiplier: 1.1, color: M,
    description: 'A cone of freezing air damages enemies before you and slows them by 50% for 6 seconds.',
    execution: { kind: 'cone', radius: 140, arc: Math.PI * 0.6, stun: 0, cc: { kind: 'slow', duration: 6, factor: 0.5 } } },
  { id: 'blizzard', name: 'Blizzard', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 8, damageMultiplier: 0.35, color: M, targetMode: 'point', range: 420, castTime: 2,
    description: 'Call down a storm of ice over the target area for 8 seconds, slowing enemies caught within.',
    execution: { kind: 'ground', effect: 'storm', radius: 140, delay: 0.5, duration: 8, interval: 1, style: 'frost', slow: { duration: 2, factor: 0.6 } } },
  { id: 'blink', name: 'Blink', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 12, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Teleport 300 units forward.',
    execution: { kind: 'step', duration: 0.15, speed: 2000 } },
  { id: 'polymorph', name: 'Polymorph', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 15, damageMultiplier: 0, color: M, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Transform your target into a harmless sheep for 8 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'polymorph', duration: 8 } },
  { id: 'counterspell', name: 'Counterspell', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 45, cooldown: 20, damageMultiplier: 0.2, color: M, targetMode: 'enemy', range: 420, offGcd: true,
    description: 'Counter your target\'s spell, interrupting it and silencing it for 5 seconds.',
    execution: { kind: 'interrupt', silence: 5 } },
  { id: 'iceBlock', name: 'Ice Block', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 15, cooldown: 120, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Encase yourself in ice, becoming immune to all damage and breaking crowd control for 6 seconds.',
    execution: { kind: 'buff', buff: { duration: 6, immunity: true, breakControl: true } } },
  { id: 'iceBarrier', name: 'Ice Barrier', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 30, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Raise a barrier of ice that absorbs damage equal to 30% of your health for 30 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, absorb: 0.3 } } },
  { id: 'evocation', name: 'Evocation', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 0, cooldown: 240, damageMultiplier: 0, color: M, targetMode: 'self',
    channel: { duration: 4, ticks: 4 },
    description: 'Channel for 4 seconds, restoring 15% of your mana per second.',
    execution: { kind: 'channel', school: 'arcane', ticks: 4, duration: 4, manaPerTick: 0.15 } },
  { id: 'mirrorImage', name: 'Mirror Image', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 60, cooldown: 90, damageMultiplier: 0, color: M, targetMode: 'self',
    description: 'Create 2 mirror images of yourself that fight beside you for 20 seconds.',
    execution: { kind: 'summon', ally: 'mirrorImage', count: 2, duration: 20 } },
  { id: 'combustion', name: 'Combustion', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 40, cooldown: 120, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Ignite your fire magic: +50% critical strike chance and +15% fire damage for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { critChance: 50, fireDamage: 15 } } } },
  { id: 'dragonsBreath', name: 'Dragon\'s Breath', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 50, cooldown: 20, damageMultiplier: 1.0, color: M,
    description: 'Breathe a cone of dragonfire, damaging and disorienting enemies before you for 3 seconds.',
    execution: { kind: 'cone', radius: 130, arc: Math.PI * 0.6, stun: 0, cc: { kind: 'incapacitate', duration: 3 } } },
  { id: 'deepFreeze', name: 'Deep Freeze', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 30, damageMultiplier: 0.4, color: M, targetMode: 'enemy', range: 420, requiresFrozen: true,
    description: 'Freeze your target solid for 4 seconds. Only usable on frozen targets.',
    execution: { kind: 'cc', cc: 'freeze', duration: 4 } },
  { id: 'flamestrike', name: 'Flamestrike', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 0, damageMultiplier: 2.0, color: M, targetMode: 'point', range: 420, castTime: 2,
    description: 'Call down a pillar of flame on the target area, leaving fire burning on the ground for 8 seconds.',
    execution: { kind: 'ground', effect: 'meteor', radius: 120, delay: 0.5, duration: 0, interval: 1, style: 'fire',
      scorch: { duration: 8, interval: 1, damageMultiplier: 0.1 } } },
  { id: 'blastWave', name: 'Blast Wave', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 30, damageMultiplier: 1.4, color: M,
    description: 'Detonate a wave of flame around you, damaging nearby enemies and slowing them by 50% for 6 seconds.',
    execution: { kind: 'radial', radius: 120, melee: false, style: 'fire', slow: { duration: 6, factor: 0.5 } } },
  { id: 'livingBomb', name: 'Living Bomb', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 50, cooldown: 0, damageMultiplier: 1.0, color: M, targetMode: 'enemy', range: 420,
    description: 'Turn your target into a living bomb, burning for 12 seconds; if it dies early, it explodes onto nearby enemies.',
    execution: { kind: 'dot', dot: { school: 'fire', dpsMultiplier: 0.2, duration: 12, detonate: 0.5 } } },
  { id: 'arcaneBlast', name: 'Arcane Blast', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 2.0, color: M, targetMode: 'enemy', range: 420, castTime: 2.5,
    description: 'Blast your target with raw arcane energy after a 2.5 second cast.',
    execution: { kind: 'projectile', speed: 650, radius: 10, offsets: [0], effects: { style: 'arcane' } } },
  { id: 'arcaneBarrage', name: 'Arcane Barrage', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 3, damageMultiplier: 1.5, color: M, targetMode: 'enemy', range: 420,
    description: 'Launch a barrage of three arcane missiles at your target.',
    execution: { kind: 'projectile', speed: 700, radius: 8, offsets: [-0.15, 0, 0.15], effects: { style: 'arcane' } } },
  { id: 'frostfireBolt', name: 'Frostfire Bolt', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 0, damageMultiplier: 2.2, color: M, targetMode: 'enemy', range: 420, castTime: 3,
    description: 'Launch a bolt of frostfire that slows your target by 40% and burns it over 4 seconds.',
    execution: { kind: 'projectile', speed: 550, radius: 12, offsets: [0],
      effects: { style: 'frost', slowFactor: 0.6, slowDuration: 4, burnDuration: 4, burnDamageMultiplier: 0.15 } } },
  { id: 'coldSnap', name: 'Cold Snap', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 480, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Snap the cold around you, restoring 30% of your mana over 6 seconds.',
    execution: { kind: 'buff', buff: { duration: 6, manaPerSecond: 0.05 } } },
  { id: 'icyVeins', name: 'Icy Veins', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 180, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Chill your veins, increasing casting speed by 20% for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, stats: { castSpeedPercent: 20 } } } },
  { id: 'arcanePower', name: 'Arcane Power', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Unleash arcane power, increasing your spell damage by 20% for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { spellDamagePercent: 20 } } } },
  { id: 'summonWaterElemental', name: 'Summon Water Elemental', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 40, cooldown: 180, damageMultiplier: 0, color: M, targetMode: 'self',
    description: 'Summon a water elemental to fight at your side for 45 seconds.',
    execution: { kind: 'summon', ally: 'waterElemental', count: 1, duration: 45 } },
  { id: 'manaShield', name: 'Mana Shield', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 12, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Shield yourself with mana, absorbing damage equal to 25% of your health for 60 seconds.',
    execution: { kind: 'ward', duration: 60, fraction: 0.25 } },
  { id: 'mageArmor', name: 'Mage Armor', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Ward yourself with mage armor, increasing all resistances and mana regeneration for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, exclusiveGroup: 'armor', stats: { allResistance: 10, manaRegen: 1 } } } },
  { id: 'moltenArmor', name: 'Molten Armor', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 55, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Sheathe yourself in molten armor, increasing critical strike chance by 3% and burning attackers for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, exclusiveGroup: 'armor', stats: { critChance: 3 }, reflect: 0.1 } } },
  { id: 'removeCurse', name: 'Remove Curse', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self',
    description: 'Remove a curse, clearing crowd control effects from yourself.',
    execution: { kind: 'cleanse', removeCc: true } },
  { id: 'spellSteal', name: 'Spell Steal', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'enemy', range: 300,
    description: 'Steal a beneficial magical effect from the target, gaining it for its remaining duration.',
    execution: { kind: 'cleanse', dispel: 1, steal: true } },
  { id: 'slowFall', name: 'Slow Fall', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 15, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Lighten your steps, increasing movement speed by 10% for 30 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, stats: { moveSpeedPercent: 10 } } } },
  { id: 'conjureRefreshment', name: 'Conjure Refreshment', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self', castTime: 3,
    description: 'Conjure refreshments, restoring 2% health and 3% mana per second for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, healPerSecond: 0.02, manaPerSecond: 0.03 } } },
  { id: 'focusMagic', name: 'Focus Magic', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Focus your magic, increasing critical strike chance by 3% for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, stats: { critChance: 3 } } } },
  { id: 'presenceOfMind', name: 'Presence of Mind', classId: 'mage', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: M, targetMode: 'self', offGcd: true,
    description: 'Clear your mind, making your next spell cast nearly instant.',
    execution: { kind: 'buff', buff: { duration: 3, stats: { castSpeedPercent: 300 } } } },
]);
