import type { WowSkill } from './skill-execution-content.ts';

const D = '#C41F3B'; // death knight class color
const FROST_FEVER = { school: 'frost' as const, dpsMultiplier: 0.12, duration: 12 };
const BLOOD_PLAGUE = { school: 'shadow' as const, dpsMultiplier: 0.12, duration: 12 };

/** Death knight kit — runes + runic power. runeCost spends runes; runicPowerGain feeds the bar. */
export const DEATHKNIGHT_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'icyTouch', name: 'Icy Touch', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 1.0, color: D, targetMode: 'enemy', range: 280,
    runeCost: { frost: 1 }, runicPowerGain: 10,
    description: 'Chill your target with Frost Fever, dealing damage over 12 seconds.',
    execution: { kind: 'runeStrike', school: 'frost', dot: FROST_FEVER } },
  { id: 'plagueStrike', name: 'Plague Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0.9, color: D, targetMode: 'enemy',
    runeCost: { unholy: 1 }, runicPowerGain: 10,
    description: 'Infect your target with Blood Plague, dealing shadow damage over 12 seconds.',
    execution: { kind: 'runeStrike', school: 'shadow', dot: BLOOD_PLAGUE } },
  { id: 'bloodStrike', name: 'Blood Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 1.2, color: D, targetMode: 'enemy',
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'A strike that deals 25% more damage per disease on the target.',
    execution: { kind: 'runeStrike', diseaseBonus: 0.25 } },
  { id: 'deathStrike', name: 'Death Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 0, damageMultiplier: 1.5, color: D, targetMode: 'enemy',
    runeCost: { frost: 1, unholy: 1 }, runicPowerGain: 15,
    description: 'A deadly strike that restores health equal to 40% of the damage dealt.',
    execution: { kind: 'runeStrike', school: 'shadow', healFrac: 0.4 } },
  { id: 'obliterate', name: 'Obliterate', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 0, damageMultiplier: 2.2, color: D, targetMode: 'enemy',
    runeCost: { frost: 1, unholy: 1 }, runicPowerGain: 15,
    description: 'A brutal strike, 25% stronger per disease on the target.',
    execution: { kind: 'runeStrike', diseaseBonus: 0.25 } },
  { id: 'scourgeStrike', name: 'Scourge Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 0, damageMultiplier: 1.8, color: D, targetMode: 'enemy',
    runeCost: { unholy: 1 }, runicPowerGain: 10,
    description: 'An unholy strike dealing shadow damage, 25% stronger per disease.',
    execution: { kind: 'runeStrike', school: 'shadow', diseaseBonus: 0.25 } },
  { id: 'deathCoil', name: 'Death Coil', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 40, cooldown: 0, damageMultiplier: 1.6, color: D, targetMode: 'enemy', range: 420,
    description: 'Hurl a coil of death energy at your target.',
    execution: { kind: 'projectile', speed: 700, radius: 10, offsets: [0], effects: { style: 'shadow' } } },
  { id: 'deathGrip', name: 'Death Grip', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 25, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 420, offGcd: true,
    description: 'Harness unholy energy to drag your target to you.',
    execution: { kind: 'pull', stun: 0.5 } },
  { id: 'chainsOfIce', name: 'Chains of Ice', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0.3, color: D, targetMode: 'enemy', range: 280,
    runeCost: { frost: 1 }, runicPowerGain: 10,
    description: 'Shackle your target with frozen chains, rooting it for 4 seconds.',
    execution: { kind: 'cc', cc: 'root', duration: 4 } },
  { id: 'mindFreeze', name: 'Mind Freeze', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 10, damageMultiplier: 0.2, color: D, targetMode: 'enemy', offGcd: true,
    description: 'Smash your target\'s mind with cold, interrupting and silencing for 4 seconds.',
    execution: { kind: 'interrupt', silence: 4 } },
  { id: 'bloodBoil', name: 'Blood Boil', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 1.0, color: D,
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Boil the blood of all nearby enemies.',
    execution: { kind: 'radial', radius: 110, melee: true } },
  { id: 'deathAndDecay', name: 'Death and Decay', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 15, damageMultiplier: 0.5, color: D, targetMode: 'point', range: 420,
    runeCost: { blood: 1, frost: 1, unholy: 1 }, runicPowerGain: 15,
    description: 'Corrupt the ground, dealing shadow damage to enemies in the area for 8 seconds.',
    execution: { kind: 'ground', effect: 'storm', radius: 120, delay: 0.3, duration: 8, interval: 1, style: 'arcane' } },
  { id: 'frostPresence', name: 'Frost Presence', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 1, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Take on a defensive presence: +30% armor, -10% damage taken.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'presence', stats: { armorPercent: 30 }, reduction: 0.1 } } },
  { id: 'bloodPresence', name: 'Blood Presence', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 1, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Take on an aggressive presence: +10% damage, 2% of damage returns as health.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'presence', stats: { damagePercent: 10, lifeOnHit: 2 } } } },
  { id: 'unholyPresence', name: 'Unholy Presence', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 1, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Take on a swift presence: +15% attack speed and movement speed.',
    execution: { kind: 'buff', buff: { duration: 3600, exclusiveGroup: 'presence', stats: { attackSpeedPercent: 15, moveSpeedPercent: 15 } } } },
  { id: 'iceboundFortitude', name: 'Icebound Fortitude', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Freeze your blood, reducing damage taken by 40% for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, reduction: 0.4 } } },
  { id: 'antiMagicShell', name: 'Anti-Magic Shell', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 20, cooldown: 45, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Surround yourself in a shell absorbing 30% of your life in damage for 5 seconds.',
    execution: { kind: 'buff', buff: { duration: 5, absorb: 0.3 } } },
  { id: 'raiseDead', name: 'Raise Dead', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 40, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Raise a ghoul to fight at your side.',
    execution: { kind: 'summon', ally: 'ghoul', count: 1 } },
  { id: 'armyOfDead', name: 'Army of the Dead', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self', castTime: 4,
    runeCost: { blood: 1, frost: 1, unholy: 1 },
    description: 'Raise a pack of ghouls to swarm your enemies for 40 seconds.',
    execution: { kind: 'summon', ally: 'ghoul', count: 4, duration: 40 } },
  { id: 'strangulate', name: 'Strangulate', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 280,
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Strangle your target with unholy strength, silencing it for 5 seconds.',
    execution: { kind: 'cc', cc: 'silence', duration: 5 } },
  { id: 'pestilence', name: 'Pestilence', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0.3, color: D,
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Spread your diseases to all nearby enemies, dealing shadow damage.',
    execution: { kind: 'radial', radius: 130, melee: false, style: 'shadow', dot: BLOOD_PLAGUE } },
  { id: 'howlingBlast', name: 'Howling Blast', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 0, cooldown: 8, damageMultiplier: 1.5, color: D, targetMode: 'point', range: 280,
    runeCost: { frost: 1, unholy: 1 }, runicPowerGain: 15,
    description: 'Blast the target area with freezing wind, dealing frost damage and slowing enemies.',
    execution: { kind: 'radial', targetRange: 280, radius: 120, melee: false, style: 'frost', slow: { duration: 3, factor: 0.5 } } },
  { id: 'frostStrike', name: 'Frost Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'advanced',
    manaCost: 40, cooldown: 0, damageMultiplier: 1.4, color: D, targetMode: 'enemy',
    description: 'A chilling strike that deals frost damage instead of physical.',
    execution: { kind: 'runeStrike', school: 'frost' } },
  { id: 'runeStrike', name: 'Rune Strike', classId: 'deathKnight', requirement: 'melee', domain: 'Might', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 1.6, color: D, targetMode: 'enemy',
    description: 'Strike the target after dodging or parrying, dealing heavy weapon damage.',
    execution: { kind: 'runeStrike' } },
  { id: 'deathchill', name: 'Deathchill', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Focus your cold fury, guaranteeing critical strikes for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, stats: { critChance: 100 } } } },
  { id: 'lichborne', name: 'Lichborne', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Draw on unholy energy to become undead, breaking and preventing crowd control for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, breakControl: true } } },
  { id: 'unbreakableArmor', name: 'Unbreakable Armor', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    runeCost: { frost: 1 }, runicPowerGain: 10,
    description: 'Reinforce your armor with frost, increasing armor by 25% and reducing damage taken for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, stats: { armorPercent: 25 }, reduction: 0.05 } } },
  { id: 'vampiricBlood', name: 'Vampiric Blood', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Increase your maximum health and leech life from your strikes for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stats: { maxHpPercent: 15 }, healPerSecond: 0.02, leech: 0.1 } } },
  { id: 'runeTap', name: 'Rune Tap', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 30, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Tap a blood rune to instantly restore 10% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.1 } },
  { id: 'markOfBlood', name: 'Mark of Blood', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Your blood marks your strikes: a portion of the damage you deal returns as healing for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, leech: 0.12 } } },
  { id: 'hysteria', name: 'Hysteria', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self',
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Drive yourself into a blood frenzy, increasing damage dealt by 20% for 30 seconds.',
    execution: { kind: 'buff', buff: { duration: 30, stats: { damagePercent: 20 } } } },
  { id: 'dancingRuneWeapon', name: 'Dancing Rune Weapon', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 0, cooldown: 90, damageMultiplier: 0, color: D, targetMode: 'self',
    runeCost: { blood: 1 }, runicPowerGain: 10,
    description: 'Summon a rune weapon that mirrors your strikes for 12 seconds.',
    execution: { kind: 'summon', ally: 'mirrorImage', count: 1, duration: 12 } },
  { id: 'summonGargoyle', name: 'Summon Gargoyle', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'ultimate',
    manaCost: 60, cooldown: 180, damageMultiplier: 0, color: D, targetMode: 'self',
    description: 'Call down a gargoyle to bombard your enemies for 30 seconds.',
    execution: { kind: 'summon', ally: 'gargoyle', count: 1, duration: 30 } },
  { id: 'corpseExplosion', name: 'Corpse Explosion', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 40, cooldown: 0, damageMultiplier: 1.2, color: D, targetMode: 'point', range: 280,
    runeCost: { unholy: 1 }, runicPowerGain: 10,
    description: 'Detonate a corpse, dealing shadow damage to all nearby enemies.',
    execution: { kind: 'radial', targetRange: 280, radius: 110, melee: false, style: 'shadow' } },
  { id: 'antiMagicZone', name: 'Anti-Magic Zone', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: D, targetMode: 'point', range: 280,
    runeCost: { unholy: 1 }, runicPowerGain: 10,
    description: 'Place a zone that reduces spell damage taken by allies inside by 75% for 10 seconds.',
    execution: { kind: 'radial', targetRange: 280, radius: 120, melee: false, style: 'arcane', shelter: { duration: 10, reduction: 0.75 } } },
  { id: 'boneShield', name: 'Bone Shield', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 60, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    runeCost: { unholy: 1 }, runicPowerGain: 10,
    description: 'Surround yourself with a barrier of whirling bones, reducing damage taken by 20% for 20 seconds.',
    execution: { kind: 'buff', buff: { duration: 20, reduction: 0.2 } } },
  { id: 'darkCommand', name: 'Dark Command', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 8, damageMultiplier: 0, color: D, targetMode: 'enemy', range: 280,
    description: 'Command the target to attack you for 3 seconds.',
    execution: { kind: 'taunt', duration: 3 } },
  { id: 'deathPact', name: 'Death Pact', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 40, cooldown: 120, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true, requiresAlly: 'ghoul',
    description: 'Sacrifice an undead minion to restore 40% of your maximum health.',
    execution: { kind: 'heal', amount: 0, maxHpFrac: 0.4, consumeAlly: 'ghoul' } },
  { id: 'hornOfWinter', name: 'Horn of Winter', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 20, damageMultiplier: 0, color: D, targetMode: 'self', runicPowerGain: 10,
    description: 'Sound the Horn of Winter, increasing strength and dexterity for 2 minutes.',
    execution: { kind: 'buff', buff: { duration: 120, stats: { strength: 10, dexterity: 10 } } } },
  { id: 'pathOfFrost', name: 'Path of Frost', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'basic',
    manaCost: 0, cooldown: 0, damageMultiplier: 0, color: D, targetMode: 'self',
    runeCost: { frost: 1 }, runicPowerGain: 10,
    description: 'Freeze the ground beneath you, granting water walking and swift movement for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, stats: { moveSpeedPercent: 10 } } } },
  { id: 'empowerRuneWeapon', name: 'Empower Rune Weapon', classId: 'deathKnight', requirement: 'any', domain: 'Might', tier: 'advanced',
    manaCost: 0, cooldown: 300, damageMultiplier: 0, color: D, targetMode: 'self', offGcd: true,
    description: 'Empower your rune weapon, rapidly regenerating runic power for 5 seconds.',
    execution: { kind: 'buff', buff: { duration: 5, resourcePerSecond: 10 } } },
]);
