import type { WowSkill } from './skill-execution-content.ts';

const P = '#FFFFFF'; // priest class color

/** Priest kit — mana-fueled holy and shadow magic. Costs are mana (class resource). */
export const PRIEST_SKILLS: readonly WowSkill[] = Object.freeze([
  { id: 'smite', name: 'Smite', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 1.4, color: P, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Hurl a bolt of holy light at your target.',
    execution: { kind: 'projectile', speed: 460, radius: 6, offsets: [0], effects: { style: 'holy' } } },
  { id: 'shadowWordPain', name: 'Shadow Word: Pain', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 0, damageMultiplier: 0.4, color: P, targetMode: 'enemy', range: 420,
    description: 'A word of darkness that deals Shadow damage over 15 seconds.',
    execution: { kind: 'dot', dot: { school: 'shadow', dpsMultiplier: 0.2, duration: 15 } } },
  { id: 'mindBlast', name: 'Mind Blast', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 8, damageMultiplier: 1.9, color: P, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Blast your target\'s mind with Shadow damage after a 1.5 second cast.',
    execution: { kind: 'strike', school: 'shadow' } },
  { id: 'mindFlay', name: 'Mind Flay', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 0, damageMultiplier: 1.2, color: P, targetMode: 'enemy', range: 280,
    channel: { duration: 3, ticks: 3 },
    description: 'Channel Shadow energy into your target for 3 seconds, slowing it by 50%.',
    execution: { kind: 'channel', school: 'shadow', ticks: 3, duration: 3, slow: { duration: 3, factor: 0.5 } } },
  { id: 'powerWordShield', name: 'Power Word: Shield', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 45, cooldown: 6, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Shield yourself, absorbing damage equal to 35% of your health for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, absorb: 0.35 } } },
  { id: 'renew', name: 'Renew', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Restore health over 12 seconds.',
    execution: { kind: 'hot', hot: { perTick: 0.15, duration: 12 } } },
  { id: 'flashHeal', name: 'Flash Heal', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 1,
    description: 'A quick heal that restores a moderate amount of health.',
    execution: { kind: 'heal', amount: 1.4 } },
  { id: 'greaterHeal', name: 'Greater Heal', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 95, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 2.5,
    description: 'A slow, powerful heal that restores a large amount of health.',
    execution: { kind: 'heal', amount: 3.2 } },
  { id: 'psychicScream', name: 'Psychic Scream', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 45, cooldown: 30, damageMultiplier: 0, color: P,
    description: 'A psychic scream that fears nearby enemies for 5 seconds.',
    execution: { kind: 'cc', cc: 'fear', duration: 5, radius: 120, maxTargets: 5 } },
  { id: 'dispelMagic', name: 'Dispel Magic', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 8, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Dispel harmful magic, removing crowd control and restoring a small amount of health.',
    execution: { kind: 'cleanse', heal: 0.05, removeCc: true } },
  { id: 'shadowform', name: 'Shadowform', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Assume a Shadowform, increasing your spell damage by 15%.',
    execution: { kind: 'form', form: 'shadow', buff: { duration: 3600, exclusiveGroup: 'form', form: 'shadow', stats: { spellDamagePercent: 15 } } } },
  { id: 'holyNova', name: 'Holy Nova', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 0, damageMultiplier: 0.8, color: P,
    description: 'A burst of holy light that damages nearby enemies and heals you for 10% of your health.',
    execution: { kind: 'radial', radius: 120, melee: false, style: 'holy', heal: 0.1 } },
  { id: 'prayerOfHealing', name: 'Prayer of Healing', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 130, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 2.5,
    description: 'A powerful prayer that heals you, then continues healing over 12 seconds.',
    execution: { kind: 'heal', amount: 2.4, hot: { perTick: 0.12, duration: 12 } } },
  { id: 'innerFire', name: 'Inner Fire', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Inner flame hardens your resolve, reducing damage taken by 5% and increasing spell damage by 10% for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, exclusiveGroup: 'armor', reduction: 0.05, stats: { spellDamagePercent: 10 } } } },
  { id: 'shadowWordDeath', name: 'Shadow Word: Death', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 12, damageMultiplier: 2.2, color: P, targetMode: 'enemy', range: 420, executeThreshold: 0.25,
    description: 'A word of death that devastates a wounded enemy. Only usable below 25% health.',
    execution: { kind: 'strike', school: 'shadow' } },
  { id: 'silence', name: 'Silence', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 35, cooldown: 45, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 420,
    description: 'Silence your target, preventing it from casting for 5 seconds.',
    execution: { kind: 'cc', cc: 'silence', duration: 5 } },
  { id: 'vampiricEmbrace', name: 'Vampiric Embrace', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 50, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Embrace the shadows: 30% of the damage you deal returns to you as healing for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, leech: 0.3 } } },
  { id: 'bindingHeal', name: 'Binding Heal', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', castTime: 1.5,
    description: 'A flash of light that binds your wounds, healing you and your target.',
    execution: { kind: 'heal', amount: 2 } },
  { id: 'circleOfHealing', name: 'Circle of Healing', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 90, cooldown: 6, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A burst of holy light that heals you and nearby allies for 15% of maximum health.',
    execution: { kind: 'heal', amount: 1.2, maxHpFrac: 0.15 } },
  { id: 'prayerOfMending', name: 'Prayer of Mending', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 10, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A prayer that mends your wounds now and continues healing over 10 seconds.',
    execution: { kind: 'heal', amount: 1, hot: { perTick: 0.2, duration: 10 } } },
  { id: 'penance', name: 'Penance', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 60, cooldown: 10, damageMultiplier: 1.5, color: P, targetMode: 'enemy', range: 420,
    channel: { duration: 2, ticks: 3 },
    description: 'Channel a volley of holy light, striking your target 3 times and mending your wounds.',
    execution: { kind: 'channel', school: 'holy', ticks: 3, duration: 2, healFrac: 0.5 } },
  { id: 'guardianSpirit', name: 'Guardian Spirit', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 60, cooldown: 180, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'A guardian spirit watches over you for 10 seconds, reducing damage taken by 40% and mending wounds.',
    execution: { kind: 'buff', buff: { duration: 10, reduction: 0.4, healPerSecond: 0.04 } } },
  { id: 'painSuppression', name: 'Pain Suppression', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 40, cooldown: 180, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Suppress all pain, reducing damage taken by 40% for 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, reduction: 0.4 } } },
  { id: 'powerInfusion', name: 'Power Infusion', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 60, cooldown: 120, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Infuse yourself with power, increasing cast speed by 20% and reducing mana costs by 20% for 15 seconds.',
    execution: { kind: 'buff', buff: { duration: 15, stats: { castSpeedPercent: 20, manaCostPercent: 20 } } } },
  { id: 'divineHymn', name: 'Divine Hymn', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 80, cooldown: 300, damageMultiplier: 1, color: P, targetMode: 'self',
    channel: { duration: 8, ticks: 4 },
    description: 'Channel a divine hymn for 8 seconds, each verse mending your wounds.',
    execution: { kind: 'channel', school: 'holy', ticks: 4, duration: 8, healFrac: 1 } },
  { id: 'hymnOfHope', name: 'Hymn of Hope', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 240, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Sing a hymn of hope, restoring mana over 8 seconds.',
    execution: { kind: 'buff', buff: { duration: 8, manaPerSecond: 0.015 } } },
  { id: 'manaBurn', name: 'Mana Burn', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 50, cooldown: 0, damageMultiplier: 1.3, color: P, targetMode: 'enemy', range: 420, castTime: 2.5,
    description: 'Blast your target\'s mind, dealing Shadow damage and silencing it for 3 seconds.',
    execution: { kind: 'strike', school: 'shadow', silence: 3 } },
  { id: 'mindControl', name: 'Mind Control', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 60, cooldown: 30, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 280, castTime: 3,
    description: 'Seize control of a humanoid\'s mind, incapacitating it for 30 seconds.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 30, family: 'humanoid' } },
  { id: 'mindSear', name: 'Mind Sear', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 0, damageMultiplier: 0.5, color: P, targetMode: 'enemy', range: 420,
    channel: { duration: 5, ticks: 5 },
    description: 'Channel shadowy tendrils into your target\'s mind for 5 seconds, searing all nearby enemies.',
    execution: { kind: 'channel', school: 'shadow', ticks: 5, duration: 5, radius: 140 } },
  { id: 'devouringPlague', name: 'Devouring Plague', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 70, cooldown: 0, damageMultiplier: 0.4, color: P, targetMode: 'enemy', range: 420,
    description: 'A plague that devours your target\'s health over 24 seconds, a portion of the strike returning to you as healing.',
    execution: { kind: 'strike', school: 'shadow', dot: { school: 'shadow', dpsMultiplier: 0.25, duration: 24 }, healFrac: 0.5 } },
  { id: 'vampiricTouch', name: 'Vampiric Touch', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 40, cooldown: 0, damageMultiplier: 0.4, color: P, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'A vampiric strike that drains your target\'s life over 15 seconds, a portion of the hit returning to you as healing.',
    execution: { kind: 'strike', school: 'shadow', dot: { school: 'shadow', dpsMultiplier: 0.3, duration: 15 }, healFrac: 0.5 } },
  { id: 'shadowfiend', name: 'Shadowfiend', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 30, cooldown: 180, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Summon a shadowfiend to fight for you for 12 seconds, restoring mana with each attack.',
    execution: { kind: 'summon', ally: 'shadowfiend', count: 1, duration: 12 } },
  { id: 'dispersion', name: 'Dispersion', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'ultimate',
    manaCost: 0, cooldown: 120, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Disperse into pure shadow for 6 seconds, reducing damage taken by 90% and restoring mana.',
    execution: { kind: 'buff', buff: { duration: 6, reduction: 0.9, form: 'shadow', manaPerSecond: 0.03 } } },
  { id: 'fade', name: 'Fade', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 25, cooldown: 30, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Fade into the shadows, dropping enemy aggression for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, stealth: true } } },
  { id: 'shackleUndead', name: 'Shackle Undead', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 40, cooldown: 30, damageMultiplier: 0, color: P, targetMode: 'enemy', range: 420, castTime: 1.5,
    description: 'Shackle an undead enemy in place, incapacitating it for 30 seconds. Any damage breaks the effect.',
    execution: { kind: 'cc', cc: 'incapacitate', duration: 30, family: 'undead' } },
  { id: 'levitate', name: 'Levitate', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 20, cooldown: 0, damageMultiplier: 0, color: P, targetMode: 'self', offGcd: true,
    description: 'Levitate above the ground, moving 10% faster for 10 minutes.',
    execution: { kind: 'buff', buff: { duration: 600, stats: { moveSpeedPercent: 10 } } } },
  { id: 'massDispel', name: 'Mass Dispel', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'advanced',
    manaCost: 90, cooldown: 15, damageMultiplier: 0, color: P, castTime: 0.5,
    description: 'Dispel magic in a wide area, breaking crowd control and restoring 15% of your health.',
    execution: { kind: 'cleanse', removeCc: true, heal: 0.15 } },
  { id: 'fearWard', name: 'Fear Ward', classId: 'priest', requirement: 'magic', domain: 'Arcana', tier: 'basic',
    manaCost: 30, cooldown: 60, damageMultiplier: 0, color: P, targetMode: 'self',
    description: 'Ward yourself against fear, breaking crowd control and negating control effects for 10 seconds.',
    execution: { kind: 'buff', buff: { duration: 10, breakControl: true } } },
]);
