import test from 'node:test';
import assert from 'node:assert/strict';
import { BIOME_IDS, startingBiome, proceduralBiomeSample } from '../src/biomes.ts';
import { landscapeFields, landscapePropProbability } from '../src/natural-landscape.ts';
import { World, WORLD_GENERATION_VERSION } from '../src/world.ts';
import { Simulation } from '../src/simulation.ts';

test('all nine climates feed the gameplay world through the shared climate sampler',()=>{
  for(const seed of [7319,18427,90210]) {
    const w=new World(seed),found=new Set<string>();
    for(let y=-36000;y<=36000;y+=960)for(let x=-36000;x<=36000;x+=960) {
      const sample=proceduralBiomeSample(x,y,seed);
      assert.deepEqual(w.sampleBiome(x,y),sample);
      if(sample.weights[sample.id]>.8)found.add(sample.id);
      assert.ok(Math.abs(Object.values(sample.weights).reduce((a,b)=>a+b,0)-1)<1e-10);
    }
    assert.deepEqual([...found].sort(),[...BIOME_IDS].sort());
    assert.equal(w.sampleBiome(0,0).id,startingBiome(seed));w.dispose();
  }
});
test('new biome actors retain their source climate and checkpoints restore their world position',()=>{
  const w=new World(7319);
  assert.equal(w.generationVersion,WORLD_GENERATION_VERSION);
  for(const id of ['steppe','sunscar'] as const){
    let point:{x:number;y:number}|undefined;
    for(let y=-10000;y<=10000&&!point;y+=400)for(let x=-10000;x<=10000;x+=400){
      if(w.sampleBiome(x,y).weights[id]>.9&&!w.blocked(x,y,20)&&!w.isSanctuary(x,y)){point={x,y};break;}
    }
    assert.ok(point,`${id} offers a clear position`);
    const sim=new Simulation(w,{spawn:false,seed:7319,startX:point.x,startY:point.y});
    const enemy=sim.spawnEnemy('stalker',point.x+50,point.y);
    assert.ok(enemy); assert.equal(enemy.biome,id);
    const checkpoint=sim.captureCheckpoint(),restored=new Simulation(w,{spawn:false,seed:7319});
    restored.restoreCheckpoint(checkpoint);
    assert.equal(restored.player.x,sim.player.x);assert.equal(restored.player.y,sim.player.y);
    assert.equal(restored.enemies[0].biome,id);
  }
  w.dispose();
});
test('groves and traversable low-density seams are smooth and have fewer blocking plants',()=>{
  let open=0,dense=0;
  for(let y=-3000;y<=3000;y+=80)for(let x=-3000;x<=3000;x+=80){
    const a=landscapeFields(x,y,7319),b=landscapeFields(x+.001,y,7319);
    for(const key of ['grove','rock','corridor'] as const)assert.ok(Math.abs(a[key]-b[key])<.001);
    const p=landscapePropProbability(x,y,7319,'tree','verdant');
    if(a.grove<.1){open++;assert.ok(p<.3);}
    if(a.grove>.7){dense++;assert.ok(p>.8);}
  }
  assert.ok(open>100&&dense>100);
});
test('each offered seed has a usable frozen scene generated by the same gameplay World',async()=>{
  const {biomeReviewScenes}=await import('../src/biome-review-data.ts');
  for(const seed of [7319,18427,90210]){
    const w=new World(seed),scenes=biomeReviewScenes(w);
    assert.ok(BIOME_IDS.every(id=>scenes.some(s=>s.id===id&&Number.isFinite(s.x)&&Number.isFinite(s.y))));
    w.dispose();
  }
});
